[[module.Buf]]
= Buf

Growing buffers

This module defines buffers that grow, with a general element type.

## Why?

Motoko applications expose interfaces that use fixed-size arrays of
general (user-defined) elements to represent sets, sequences and maps
of application-specific elements.

The `Array` module focuses on Motoko's builtin arrays, whose size is
each fixed.  They do not permit general growth/appending, which is the
focus here.

To create these arrays, and to consume them with ergonomic (imperative) code, and
low API friction, developers need _buffers that grow_.

## Define `Buf<X>` object type

A "buffer" is a mutable sequence that grows, either one element at a
time, or one (second) buffer at time.

[[class.Buf]]
== Buf

Create a buffer represented internally by an mutable array.

The argument `initCapacity` gives the initial capacity.  Under the
interface, the mutable array grows by doubling when this initial
capacity is exhausted.

[source,motoko]
----
class Buf<X>(initCapacity : Nat)
----



[[value.add]]
=== add



[source,motoko]
----
func add(elem : X)
----

[[value.removeLast]]
=== removeLast



[source,motoko]
----
func removeLast() : ?X
----

[[value.append]]
=== append



[source,motoko]
----
func append(b : Buf<X>)
----

[[value.size]]
=== size



[source,motoko]
----
func size() : Nat
----

[[value.clear]]
=== clear



[source,motoko]
----
func clear()
----

[[value.clone]]
=== clone



[source,motoko]
----
func clone() : Buf<X>
----

[[value.vals]]
=== vals



[source,motoko]
----
func vals() : { next : () -> ?X }
----

[[value.toArray]]
=== toArray



[source,motoko]
----
func toArray() : [X]
----

[[value.toVarArray]]
=== toVarArray



[source,motoko]
----
func toVarArray() : [var X]
----

[[value.get]]
=== get



[source,motoko]
----
func get(offset : Nat) : X
----

[[value.getOpt]]
=== getOpt



[source,motoko]
----
func getOpt(offset : Nat) : ?X
----

[[value.put]]
=== put



[source,motoko]
----
func put(offset : Nat, elem : X)
----

