[[module.Float]]
= Float

64-bit Floating-point numbers

[[value.pi]]
== pi

Ratio of the circumference of a circle to its diameter.

[source,motoko]
----
let pi : Float
----

[[value.e]]
== e

Base of the natural logarithm.

[source,motoko]
----
let e : Float
----

[[value.abs]]
== abs

Returns the absolute value of `x`.

[source,motoko]
----
let abs : ((x : Float)) -> Float
----

[[value.sqrt]]
== sqrt

Returns the square root of `x`.

[source,motoko]
----
let sqrt : ((x : Float)) -> Float
----

[[value.ceil]]
== ceil

Returns the smallest integral float greater than or equal to `x`.

[source,motoko]
----
let ceil : ((x : Float)) -> Float
----

[[value.floor]]
== floor

Returns the largest integral float less than or equal to `x`.

[source,motoko]
----
let floor : ((x : Float)) -> Float
----

[[value.trunc]]
== trunc

Returns the nearest integral float not greater in magnitude than `x`.

[source,motoko]
----
let trunc : ((x : Float)) -> Float
----

[[value.nearest]]
== nearest

Returns the nearest integral float to `x`.

[source,motoko]
----
let nearest : ((x : Float)) -> Float
----

[[value.copySign]]
== copySign

Returns `x` if `x` and `y` have same sign, otherwise `x` with negated sign.

[source,motoko]
----
let copySign : (x : Float, y : Float) -> Float
----

[[value.min]]
== min

Returns the smaller value of `x` and `y`.

[source,motoko]
----
let min : (x : Float, y : Float) -> Float
----

[[value.max]]
== max

Returns the larger value of `x` and `y`.

[source,motoko]
----
let max : (x : Float, y : Float) -> Float
----

[[value.sin]]
== sin

Returns the sine of the radian angle `x`.

[source,motoko]
----
let sin : ((x : Float)) -> Float
----

[[value.cos]]
== cos

Returns the cosine of the radian angle `x`.

[source,motoko]
----
let cos : ((x : Float)) -> Float
----

[[value.tan]]
== tan

Returns the tangent of the radian angle `x`.

[source,motoko]
----
let tan : ((x : Float)) -> Float
----

[[value.arcsin]]
== arcsin

Returns the arc sine of `x` in radians.

[source,motoko]
----
let arcsin : ((x : Float)) -> Float
----

[[value.arccos]]
== arccos

Returns the arc cosine of `x` in radians.

[source,motoko]
----
let arccos : ((x : Float)) -> Float
----

[[value.arctan]]
== arctan

Returns the arc tangent in `x` in radians.

[source,motoko]
----
let arctan : ((x : Float)) -> Float
----

[[value.arctan2]]
== arctan2

Given `(y,x)`, returns the arc tangent in radians of `y/x` based on the signs of both values to determine the correct quadrant.

[source,motoko]
----
let arctan2 : (y : Float, x : Float) -> Float
----

[[value.exp]]
== exp

Returns the value of `e` raised to the `x`-th power.

[source,motoko]
----
let exp : ((x : Float)) -> Float
----

[[value.log]]
== log

Returns the natural logarithm (base-`e`) of `x`.

[source,motoko]
----
let log : ((x : Float)) -> Float
----

[[value.toText]]
== toText

Conversion.

[source,motoko]
----
let toText : (Float) -> Text
----

[[value.toInt64]]
== toInt64

Conversion.

[source,motoko]
----
let toInt64 : (Float) -> Int64
----

[[value.fromInt64]]
== fromInt64

Conversion.

[source,motoko]
----
let fromInt64 : (Int64) -> Float
----

[[value.toInt]]
== toInt

Conversion via Int64.

[source,motoko]
----
let toInt : (Float) -> Int
----

[[value.fromInt]]
== fromInt

Conversion via Int64. May trap.

[source,motoko]
----
let fromInt : (Int) -> Float
----

[[value.equal]]
== equal

Returns `x == y`.

[source,motoko]
----
func equal(x : Float, y : Float) : Bool
----

[[value.notEqual]]
== notEqual

Returns `x != y`.

[source,motoko]
----
func notEqual(x : Float, y : Float) : Bool
----

[[value.less]]
== less

Returns `x < y`.

[source,motoko]
----
func less(x : Float, y : Float) : Bool
----

[[value.lessOrEqual]]
== lessOrEqual

Returns `x <= y`.

[source,motoko]
----
func lessOrEqual(x : Float, y : Float) : Bool
----

[[value.greater]]
== greater

Returns `x > y`.

[source,motoko]
----
func greater(x : Float, y : Float) : Bool
----

[[value.greaterOrEqual]]
== greaterOrEqual

Returns `x >= y`.

[source,motoko]
----
func greaterOrEqual(x : Float, y : Float) : Bool
----

[[value.compare]]
== compare

Returns the order of `x` and `y`.

[source,motoko]
----
func compare(x : Float, y : Float) : {#less : (); #equal : (); #greater : ()}
----

[[value.neq]]
== neq

Returns the negation of `x`, `-x` .

[source,motoko]
----
func neq(x : Float) : Float
----

[[value.add]]
== add

Returns the sum of `x` and `y`, `x + y`.

[source,motoko]
----
func add(x : Float, y : Float) : Float
----

[[value.sub]]
== sub

Returns the difference of `x` and `y`, `x - y`.

[source,motoko]
----
func sub(x : Float, y : Float) : Float
----

[[value.mul]]
== mul

Returns the product of `x` and `y`, `x * y`.

[source,motoko]
----
func mul(x : Float, y : Float) : Float
----

[[value.div]]
== div

Returns the division of `x` by `y`, `x / y`.

[source,motoko]
----
func div(x : Float, y : Float) : Float
----

[[value.rem]]
== rem

Returns the remainder of `x` divided by `y`, `x % y`.

[source,motoko]
----
func rem(x : Float, y : Float) : Float
----

[[value.pow]]
== pow

Returns `x` to the power of `y`, `x ** y`.

[source,motoko]
----
func pow(x : Float, y : Float) : Float
----

