[[module.Int]]
= Int

Integer numbers

Most operations on natural numbers (e.g. addition) are available as built-in operators (`1 + 1`).
This module provides equivalent functions and conversion functions.

The conversions `toInt*` will trap if the number is out of bounds.

[[value.abs]]
== abs

Returns the absolute value of the number

[source,motoko]
----
let abs : (Int) -> Nat
----

[[value.toText]]
== toText



[source,motoko]
----
let toText : (Int) -> Text
----

[[value.min]]
== min

Returns the minimum of `x` and `y`.

[source,motoko]
----
func min(x : Int, y : Int) : Int
----

[[value.max]]
== max

Returns the maximum of `x` and `y`.

[source,motoko]
----
func max(x : Int, y : Int) : Int
----

[[value.hash]]
== hash



[source,motoko]
----
func hash(i : Int) : Hash.Hash
----

[[value.hashAcc]]
== hashAcc

WARNING: May go away (?)

[source,motoko]
----
func hashAcc(h1 : Hash.Hash, i : Int) : Hash.Hash
----

[[value.equal]]
== equal

Returns `x == y`.

[source,motoko]
----
func equal(x : Int, y : Int) : Bool
----

[[value.notEqual]]
== notEqual

Returns `x != y`.

[source,motoko]
----
func notEqual(x : Int, y : Int) : Bool
----

[[value.less]]
== less

Returns `x < y`.

[source,motoko]
----
func less(x : Int, y : Int) : Bool
----

[[value.lessOrEqual]]
== lessOrEqual

Returns `x <= y`.

[source,motoko]
----
func lessOrEqual(x : Int, y : Int) : Bool
----

[[value.greater]]
== greater

Returns `x > y`.

[source,motoko]
----
func greater(x : Int, y : Int) : Bool
----

[[value.greaterOrEqual]]
== greaterOrEqual

Returns `x >= y`.

[source,motoko]
----
func greaterOrEqual(x : Int, y : Int) : Bool
----

[[value.compare]]
== compare

Returns the order of `x` and `y`.

[source,motoko]
----
func compare(x : Int, y : Int) : {#less : (); #equal : (); #greater : ()}
----

[[value.neq]]
== neq

Returns the negation of `x`, `-x` .

[source,motoko]
----
func neq(x : Int) : Int
----

[[value.add]]
== add

Returns the sum of `x` and `y`, `x + y`.

[source,motoko]
----
func add(x : Int, y : Int) : Int
----

[[value.sub]]
== sub

Returns the difference of `x` and `y`, `x - y`.

[source,motoko]
----
func sub(x : Int, y : Int) : Int
----

[[value.mul]]
== mul

Returns the product of `x` and `y`, `x * y`.

[source,motoko]
----
func mul(x : Int, y : Int) : Int
----

[[value.div]]
== div

Returns the division of `x` by `y`,  `x / y`.

[source,motoko]
----
func div(x : Int, y : Int) : Int
----

[[value.rem]]
== rem

Returns the remainder of `x` divided by `y`, `x % y`.

[source,motoko]
----
func rem(x : Int, y : Int) : Int
----

[[value.pow]]
== pow

Returns `x` to the power of `y`, `x ** y`.

[source,motoko]
----
func pow(x : Int, y : Int) : Int
----

