[[module.Nat8]]
= Nat8

8-bit unsigned integers with checked arithmetic

Most operations are available as built-in operators (e.g. `1 + 1`).

[[value.toNat]]
== toNat

Conversion.

[source,motoko]
----
let toNat : Nat8 -> Nat
----

[[value.fromNat]]
== fromNat

Conversion. Traps on overflow/underflow.

[source,motoko]
----
let fromNat : Nat -> Nat8
----

[[value.toText]]
== toText

Returns the Text representation of `x`.

[source,motoko]
----
func toText(x : Nat8) : Text
----

[[value.min]]
== min

Returns the minimum of `x` and `y`.

[source,motoko]
----
func min(x : Nat8, y : Nat8) : Nat8
----

[[value.max]]
== max

Returns the maximum of `x` and `y`.

[source,motoko]
----
func max(x : Nat8, y : Nat8) : Nat8
----

[[value.equal]]
== equal

Returns `x == y`.

[source,motoko]
----
func equal(x : Nat8, y : Nat8) : Bool
----

[[value.notEqual]]
== notEqual

Returns `x != y`.

[source,motoko]
----
func notEqual(x : Nat8, y : Nat8) : Bool
----

[[value.less]]
== less

Returns `x < y`.

[source,motoko]
----
func less(x : Nat8, y : Nat8) : Bool
----

[[value.lessOrEqual]]
== lessOrEqual

Returns `x <= y`.

[source,motoko]
----
func lessOrEqual(x : Nat8, y : Nat8) : Bool
----

[[value.greater]]
== greater

Returns `x > y`.

[source,motoko]
----
func greater(x : Nat8, y : Nat8) : Bool
----

[[value.greaterOrEqual]]
== greaterOrEqual

Returns `x >= y`.

[source,motoko]
----
func greaterOrEqual(x : Nat8, y : Nat8) : Bool
----

[[value.compare]]
== compare

Returns the order of `x` and `y`.

[source,motoko]
----
func compare(x : Nat8, y : Nat8) : {#less; #equal; #greater}
----

[[value.add]]
== add

Returns the sum of `x` and `y`, `x + y`. Traps on overflow.

[source,motoko]
----
func add(x : Nat8, y : Nat8) : Nat8
----

[[value.sub]]
== sub

Returns the difference of `x` and `y`, `x - y`. Traps on underflow.

[source,motoko]
----
func sub(x : Nat8, y : Nat8) : Nat8
----

[[value.mul]]
== mul

Returns the product of `x` and `y`, `x * y`. Traps on overflow.

[source,motoko]
----
func mul(x : Nat8, y : Nat8) : Nat8
----

[[value.div]]
== div

Returns the division of `x by y`, `x / y`.
Traps when `y` is zero.

[source,motoko]
----
func div(x : Nat8, y : Nat8) : Nat8
----

[[value.rem]]
== rem

Returns the remainder of `x` divided by `y`, `x % y`.
Traps when `y` is zero.

[source,motoko]
----
func rem(x : Nat8, y : Nat8) : Nat8
----

[[value.pow]]
== pow

Returns `x` to the power of `y`, `x ** y`. Traps on overflow.

[source,motoko]
----
func pow(x : Nat8, y : Nat8) : Nat8
----

