[[module.Option]]
= Option

Typesafe nulls

Optional values can be seen as a typesafe `null`. A value of type ?(Int) can
be constructed with either `null` or `?(42)`. The simplest way to get at
the contents of an optional is to use pattern matching:

```motoko
let optionalInt1 : ?(Int) = ?(42);
let optionalInt2 : ?(Int) = null;

let int1orZero : Int = switch(optionalInt1) {
  case null 0;
  case ?(int) int;
};
assertEquals(int1OrZero, 42);

let int2orZero : Int = switch(optionalInt2) {
  case null 0;
  case ?(int) int;
};
assertEquals(int2OrZero, 0);
```

The functions in this module capture some common operations when working
with optionals that can be more succinct than using pattern matching.

[[value.get]]
== get

Unwraps an optional value, with a default value, i.e. `get(?x, d) = x` and
`get(null, d) = d`.

[source,motoko]
----
func get<T>(x : ?T, default : T) : T
----

[[value.getMapped]]
== getMapped

Unwraps an optional value using a function, or returns the default, i.e.
`option(?x, f, d) = f x` and `option(null, f, d) = d`.

[source,motoko]
----
func getMapped<A, B>(x : ?A, f : (A) -> B, default : B) : B
----

[[value.map]]
== map

Applies a function to the wrapped value. `null`'s are left untouched.
```
map(f, ?(x)) = ?(f(x))
map(f, null) = null
```

[source,motoko]
----
func map<A, B>(f : (A) -> B, x : ?A) : ?B
----

[[value.apply]]
== apply

Applies an optional function to an optional value. Returns `null` if at
least one of the arguments is `null`.

[source,motoko]
----
func apply<A, B>(x : ?A, f : ?((A) -> B)) : ?B
----

[[value.chain]]
== chain

Applies a function to an optional value. Returns `null` if the argument is
`null`, or the function returns `null`.

NOTE: Together with [`make`](#value.make), this forms a “monad”.

[source,motoko]
----
func chain<A, B>(x : ?A, f : (A) -> ?B) : ?B
----

[[value.flatten]]
== flatten

Given an optional optional value, removes one layer of optionality.
```
flatten(?(?(42)))) = ?(42)
flatten(?(null))) = null
flatten(null)) = null
```

[source,motoko]
----
func flatten<A>(x : ?(?A)) : ?A
----

[[value.make]]
== make

Creates an optional value from a definite value.
```
make(42) = ?(42)
```

[source,motoko]
----
func make<A>(x : A) : ?A
----

[[value.isSome]]
== isSome

Returns true if the argument is not `null`, otherwise returns false.

[source,motoko]
----
func isSome(x : ?Any) : Bool
----

[[value.isNull]]
== isNull

Returns true if the argument is `null`, otherwise returns false.

[source,motoko]
----
func isNull(x : ?Any) : Bool
----

[[value.assertSome]]
== assertSome

Asserts that the value is not `null`; fails otherwise.
Deprecated.

[source,motoko]
----
func assertSome(x : ?Any)
----

[[value.assertNull]]
== assertNull

Asserts that the value _is_ `null`; fails otherwise.
Deprecated.

[source,motoko]
----
func assertNull(x : ?Any)
----

[[value.unwrap]]
== unwrap

Unwraps an optional value, i.e. `unwrap(?x) = x`.

WARNING: `unwrap(x)` will fail if the argument is `null`, and is generally considered bad style. Use `switch x` instead.

[source,motoko]
----
func unwrap<T>(x : ?T) : T
----

