[[module.RBTree]]
= RBTree

Red-Black Trees

[[type.Color]]
== Color

Node color: Red or black.

[source,motoko]
----
type Color = {#R; #B}
----

[[type.Tree]]
== Tree

Ordered, (red-black) tree of entries.

[source,motoko]
----
type Tree<X, Y> = {#node : (Color, Tree<X, Y>, (X, ?Y), Tree<X, Y>); #leaf}
----

[[class.RBTree]]
== RBTree

Create an order map from an order function for its keys.

[source,motoko]
----
class RBTree<X, Y>(compareTo : (X, X) -> O.Order)
----



[[value.share]]
=== share

Tree as share data.

Get non-OO, purely-functional representation:
for drawing, pretty-printing and non-OO contexts
(e.g., async args and results):

[source,motoko]
----
func share() : Tree<X, Y>
----

[[value.get]]
=== get

Get the value associated with a given key.

[source,motoko]
----
func get(x : X) : ?Y
----

[[value.replace]]
=== replace

Replace the value associated with a given key.

[source,motoko]
----
func replace(x : X, y : Y) : ?Y
----

[[value.put]]
=== put

Put an entry: A value associated with a given key.

[source,motoko]
----
func put(x : X, y : Y)
----

[[value.delete]]
=== delete

Delete the entry associated with a given key.

[source,motoko]
----
func delete(x : X)
----

[[value.remove]]
=== remove

Remove the entry associated with a given key.

[source,motoko]
----
func remove(x : X) : ?Y
----

[[value.entries]]
=== entries

An iterator for the key-value entries of the map, in ascending key order.

iterator is persistent, like the tree itself

[source,motoko]
----
func entries() : I.Iter<(X, Y)>
----

[[value.entriesRev]]
=== entriesRev

An iterator for the key-value entries of the map, in descending key order.

iterator is persistent, like the tree itself

[source,motoko]
----
func entriesRev() : I.Iter<(X, Y)>
----

[[value.iter]]
== iter

An iterator for the entries of the map, in ascending (`#fwd`) or descending (`#bwd`) order.

[source,motoko]
----
func iter<X, Y>(t : Tree<X, Y>, dir : {#fwd; #bwd}) : I.Iter<(X, Y)>
----

[[value.size]]
== size

The size of the tree as the number of key-value entries.

[source,motoko]
----
func size<X, Y>(t : Tree<X, Y>) : Nat
----

