[[module.Word16]]
= Word16

16-bit binary unsigned integers with modular arithmetic

Most operations are available as built-in operators (e.g. `1 | 1`).

[[value.toNat]]
== toNat

Conversion.

[source,motoko]
----
let toNat : (Word16) -> Nat
----

[[value.fromNat]]
== fromNat

Conversion. Wraps around.

[source,motoko]
----
let fromNat : (Nat) -> Word16
----

[[value.toInt]]
== toInt

Conversion. Returns `x mod 2^16`.

[source,motoko]
----
let toInt : ((x : Word16)) -> Int
----

[[value.fromInt]]
== fromInt

Conversion. Returns `x mod 2^16`.

[source,motoko]
----
let fromInt : ((x : Int)) -> Word16
----

[[value.toText]]
== toText

Returns the Text representation of `x`.

[source,motoko]
----
func toText(x : Word16) : Text
----

[[value.min]]
== min

Returns the minimum of `x` and `y`.

[source,motoko]
----
func min(x : Word16, y : Word16) : Word16
----

[[value.max]]
== max

Returns the maximum of `x` and `y`.

[source,motoko]
----
func max(x : Word16, y : Word16) : Word16
----

[[value.equal]]
== equal

Returns `x == y`.

[source,motoko]
----
func equal(x : Word16, y : Word16) : Bool
----

[[value.notEqual]]
== notEqual

Returns `x != y`.

[source,motoko]
----
func notEqual(x : Word16, y : Word16) : Bool
----

[[value.less]]
== less

Returns `x < y`.

[source,motoko]
----
func less(x : Word16, y : Word16) : Bool
----

[[value.lessOrEqual]]
== lessOrEqual

Returns `x <= y`.

[source,motoko]
----
func lessOrEqual(x : Word16, y : Word16) : Bool
----

[[value.greater]]
== greater

Returns `x > y`.

[source,motoko]
----
func greater(x : Word16, y : Word16) : Bool
----

[[value.greaterOrEqual]]
== greaterOrEqual

Returns `x >= y`.

[source,motoko]
----
func greaterOrEqual(x : Word16, y : Word16) : Bool
----

[[value.compare]]
== compare

Returns the order of `x` and `y`.

[source,motoko]
----
func compare(x : Word16, y : Word16) : {#less : (); #equal : (); #greater : ()}
----

[[value.add]]
== add

Returns the sum of `x` and `y`, `(x + y) mod 2^16`.

[source,motoko]
----
func add(x : Word16, y : Word16) : Word16
----

[[value.sub]]
== sub

Returns the difference of `x` and `y`, `(2^16 + x - y) mod 2^16`.

[source,motoko]
----
func sub(x : Word16, y : Word16) : Word16
----

[[value.mul]]
== mul

Returns the product of `x` and `y`, `(x * y) mod 2^16`.

[source,motoko]
----
func mul(x : Word16, y : Word16) : Word16
----

[[value.div]]
== div

Returns the division of `x` by `y`, `x / y`.
Traps when `y` is zero.

[source,motoko]
----
func div(x : Word16, y : Word16) : Word16
----

[[value.rem]]
== rem

Returns the remainder of `x` divided by `y`, `x % y`.
Traps when `y` is zero.

[source,motoko]
----
func rem(x : Word16, y : Word16) : Word16
----

[[value.pow]]
== pow

Returns `x` to the power of `y`, `(x ** y) mod 2^16`.

[source,motoko]
----
func pow(x : Word16, y : Word16) : Word16
----

[[value.bitnot]]
== bitnot

Returns the bitwise negation of `x`, `^x`.

[source,motoko]
----
func bitnot(x : Word16, y : Word16) : Word16
----

[[value.bitand]]
== bitand

Returns the bitwise and of `x` and `y`, `x & y`.

[source,motoko]
----
func bitand(x : Word16, y : Word16) : Word16
----

[[value.bitor]]
== bitor

Returns the bitwise or of `x` and `y`, `x \| y`.

[source,motoko]
----
func bitor(x : Word16, y : Word16) : Word16
----

[[value.bitxor]]
== bitxor

Returns the bitwise exclusive or of `x` and `y`, `x ^ y`.

[source,motoko]
----
func bitxor(x : Word16, y : Word16) : Word16
----

[[value.bitshiftLeft]]
== bitshiftLeft

Returns the bitwise shift left of `x` by `y`, `x << y`.

[source,motoko]
----
func bitshiftLeft(x : Word16, y : Word16) : Word16
----

[[value.bitshiftRight]]
== bitshiftRight

Returns the bitwise shift right of `x` by `y`, `x >> y`.

[source,motoko]
----
func bitshiftRight(x : Word16, y : Word16) : Word16
----

[[value.bitshiftRightSigned]]
== bitshiftRightSigned

Returns the signed shift right of `x` by `y`, `x +>> y`.

[source,motoko]
----
func bitshiftRightSigned(x : Word16, y : Word16) : Word16
----

[[value.bitrotLeft]]
== bitrotLeft

Returns the bitwise rotate left of `x` by `y`, `x <<> y`.

[source,motoko]
----
func bitrotLeft(x : Word16, y : Word16) : Word16
----

[[value.bitrotRight]]
== bitrotRight

Returns the bitwise rotate right of `x` by `y`, `x <>> y`.

[source,motoko]
----
func bitrotRight(x : Word16, y : Word16) : Word16
----

[[value.bittest]]
== bittest

Returns the value of bit `p mod 16` in `x`, `(x & 2^(p mod 16)) == 2^(p mod 16)`.

[source,motoko]
----
func bittest(x : Word16, p : Nat) : Bool
----

[[value.bitset]]
== bitset

Returns the value of setting bit `p mod 16` in `x` to `1`.

[source,motoko]
----
func bitset(x : Word16, p : Nat) : Word16
----

[[value.bitclear]]
== bitclear

Returns the value of clearing bit `p mod 16` in `x` to `0`.

[source,motoko]
----
func bitclear(x : Word16, p : Nat) : Word16
----

[[value.bitflip]]
== bitflip

Returns the value of flipping bit `p mod 16` in `x`.

[source,motoko]
----
func bitflip(x : Word16, p : Nat) : Word16
----

[[value.bitcountNonZero]]
== bitcountNonZero

Returns the count of non-zero bits in `x`.

[source,motoko]
----
let bitcountNonZero : ((x : Word16)) -> Word16
----

[[value.bitcountLeadingZero]]
== bitcountLeadingZero

Returns the count of leading zero bits in `x`.

[source,motoko]
----
let bitcountLeadingZero : ((x : Word16)) -> Word16
----

[[value.bitcountTrailingZero]]
== bitcountTrailingZero

Returns the count of trailing zero bits in `x`.

[source,motoko]
----
let bitcountTrailingZero : ((x : Word16)) -> Word16
----

