[[module.AssocList]]
= AssocList

Lists of key-value entries ("associations").

Implements the same operations as library `Trie`, but uses a
linked-list of entries and no hashing.

[[type.AssocList]]
== AssocList

[source.no-repl,motoko,subs=+macros]
----
type AssocList<K, V> = xref:List.adoc#type.List[List.List]<(K, V)>
----

polymorphic association linked lists between keys and values

[[find]]
== find

[source.no-repl,motoko,subs=+macros]
----
func find<K, V>(al : xref:#type.AssocList[AssocList]<K, V>, k : K, k_eq : (K, K) -> Bool) : ?V
----

Find the value associated with a given key, or null if absent.

[[replace]]
== replace

[source.no-repl,motoko,subs=+macros]
----
func replace<K, V>(al : xref:#type.AssocList[AssocList]<K, V>, k : K, k_eq : (K, K) -> Bool, ov : ?V) : (xref:#type.AssocList[AssocList]<K, V>, ?V)
----

replace the value associated with a given key, or add it, if missing.
returns old value, or null, if no prior value existed.

[[diff]]
== diff

[source.no-repl,motoko,subs=+macros]
----
func diff<K, V, W>(al1 : xref:#type.AssocList[AssocList]<K, V>, al2 : xref:#type.AssocList[AssocList]<K, W>, keq : (K, K) -> Bool) : xref:#type.AssocList[AssocList]<K, V>
----

The entries of the final list consist of those pairs of
the left list whose keys are not present in the right list; the
"extra" values of the right list are irrelevant.

[[mapAppend]]
== mapAppend

[source.no-repl,motoko,subs=+macros]
----
func mapAppend<K, V, W, X>(al1 : xref:#type.AssocList[AssocList]<K, V>, al2 : xref:#type.AssocList[AssocList]<K, W>, vbin : (?V, ?W) -> X) : xref:#type.AssocList[AssocList]<K, X>
----

Transform and combine the entries of two association lists.

[[disjDisjoint]]
== disjDisjoint

[source.no-repl,motoko,subs=+macros]
----
func disjDisjoint<K, V, W, X>(al1 : xref:#type.AssocList[AssocList]<K, V>, al2 : xref:#type.AssocList[AssocList]<K, W>, vbin : (?V, ?W) -> X) : xref:#type.AssocList[AssocList]<K, X>
----

Specialized version of `disj`, optimized for disjoint sub-spaces of keyspace (no matching keys).

[[disj]]
== disj

[source.no-repl,motoko,subs=+macros]
----
func disj<K, V, W, X>(al1 : xref:#type.AssocList[AssocList]<K, V>, al2 : xref:#type.AssocList[AssocList]<K, W>, keq : (K, K) -> Bool, vbin : (?V, ?W) -> X) : xref:#type.AssocList[AssocList]<K, X>
----

This operation generalizes the notion of "set union" to finite maps.
Produces a "disjunctive image" of the two lists, where the values of
matching keys are combined with the given binary operator.

For unmatched entries, the operator is still applied to
create the value in the image.  To accomodate these various
situations, the operator accepts optional values, but is never
applied to (null, null).

[[join]]
== join

[source.no-repl,motoko,subs=+macros]
----
func join<K, V, W, X>(al1 : xref:#type.AssocList[AssocList]<K, V>, al2 : xref:#type.AssocList[AssocList]<K, W>, keq : (K, K) -> Bool, vbin : (V, W) -> X) : xref:#type.AssocList[AssocList]<K, X>
----

This operation generalizes the notion of "set intersection" to
finite maps.  Produces a "conjuctive image" of the two lists, where
the values of matching keys are combined with the given binary
operator, and unmatched entries are not present in the output.

[[fold]]
== fold

[source.no-repl,motoko,subs=+macros]
----
func fold<K, V, X>(al : xref:#type.AssocList[AssocList]<K, V>, nil : X, cons : (K, V, X) -> X) : X
----

Fold the entries based on the recursive list structure.

