[[module.Buffer]]
= Buffer

Generic, extensible buffers

Generic, mutable sequences that grow to accommodate arbitrary numbers of elements.

Class `Buffer<X>` provides extensible, mutable sequences of elements of type `X`.
that can be efficiently produced and consumed with imperative code.
A buffer object can be extended by a single element or the contents of another buffer object.

When required, the current state of a buffer object can be converted to a fixed-size array of its elements.

Buffers complement Motoko's non-extensible array types
(arrays do not support efficient extension, because the size of an array is
determined at construction and cannot be changed).

[[type.Buffer]]
== Buffer

[source.no-repl,motoko,subs=+macros]
----
class Buffer<X>(initCapacity : Nat)
----

Create a stateful buffer class encapsulating a mutable array.

The argument `initCapacity` determines its initial capacity.
The underlying mutable array grows by doubling when its current
capacity is exceeded.



[[Buffer.add]]
=== add

[source.no-repl,motoko,subs=+macros]
----
func add(elem : X)
----

Adds a single element to the buffer.

[[Buffer.removeLast]]
=== removeLast

[source.no-repl,motoko,subs=+macros]
----
func removeLast() : ?X
----

Removes the item that was inserted last and returns it or `null` if no
elements had been added to the Buffer.

[[Buffer.append]]
=== append

[source.no-repl,motoko,subs=+macros]
----
func append(b : xref:#type.Buffer[Buffer]<X>)
----

Adds all elements in buffer `b` to this buffer.

[[Buffer.size]]
=== size

[source.no-repl,motoko,subs=+macros]
----
func size() : Nat
----

Returns the current number of elements.

[[Buffer.clear]]
=== clear

[source.no-repl,motoko,subs=+macros]
----
func clear()
----

Resets the buffer.

[[Buffer.clone]]
=== clone

[source.no-repl,motoko,subs=+macros]
----
func clone() : xref:#type.Buffer[Buffer]<X>
----

Returns a copy of this buffer.

[[Buffer.vals]]
=== vals

[source.no-repl,motoko,subs=+macros]
----
func vals() : { next : () -> ?X }
----

Returns an `Iter` over the elements of this buffer.

[[Buffer.toArray]]
=== toArray

[source.no-repl,motoko,subs=+macros]
----
func toArray() : pass:[[]Xpass:[]]
----

Creates a new array containing this buffer's elements.

[[Buffer.toVarArray]]
=== toVarArray

[source.no-repl,motoko,subs=+macros]
----
func toVarArray() : pass:[[]var Xpass:[]]
----

Creates a mutable array containing this buffer's elements.

[[Buffer.get]]
=== get

[source.no-repl,motoko,subs=+macros]
----
func get(i : Nat) : X
----

Gets the `i`-th element of this buffer. Traps if  `i >= count`. Indexing is zero-based.

[[Buffer.getOpt]]
=== getOpt

[source.no-repl,motoko,subs=+macros]
----
func getOpt(i : Nat) : ?X
----

Gets the `i`-th element of the buffer as an option. Returns `null` when `i >= count`. Indexing is zero-based.

[[Buffer.put]]
=== put

[source.no-repl,motoko,subs=+macros]
----
func put(i : Nat, elem : X)
----

Overwrites the current value of the `i`-entry of  this buffer with `elem`. Traps if the
index is out of bounds. Indexing is zero-based.

[[fromArray]]
== fromArray

[source.no-repl,motoko,subs=+macros]
----
func fromArray<X>(elems : pass:[[]Xpass:[]]) : xref:#type.Buffer[Buffer]<X>
----

Creates a buffer from immutable array elements.

[[fromVarArray]]
== fromVarArray

[source.no-repl,motoko,subs=+macros]
----
func fromVarArray<X>(elems : pass:[[]var Xpass:[]]) : xref:#type.Buffer[Buffer]<X>
----

Creates a buffer from the elements of a mutable array.

