[[module.Float]]
= Float

64-bit Floating-point numbers

[[value.pi]]
== pi

[source.no-repl,motoko]
----
let pi : Float
----

Ratio of the circumference of a circle to its diameter.

[[value.e]]
== e

[source.no-repl,motoko]
----
let e : Float
----

Base of the natural logarithm.

[[value.abs]]
== abs

[source.no-repl,motoko]
----
let abs : (x : Float) -> Float
----

Returns the absolute value of `x`.

[[value.sqrt]]
== sqrt

[source.no-repl,motoko]
----
let sqrt : (x : Float) -> Float
----

Returns the square root of `x`.

[[value.ceil]]
== ceil

[source.no-repl,motoko]
----
let ceil : (x : Float) -> Float
----

Returns the smallest integral float greater than or equal to `x`.

[[value.floor]]
== floor

[source.no-repl,motoko]
----
let floor : (x : Float) -> Float
----

Returns the largest integral float less than or equal to `x`.

[[value.trunc]]
== trunc

[source.no-repl,motoko]
----
let trunc : (x : Float) -> Float
----

Returns the nearest integral float not greater in magnitude than `x`.

[[value.nearest]]
== nearest

[source.no-repl,motoko]
----
let nearest : (x : Float) -> Float
----

Returns the nearest integral float to `x`.

[[value.copySign]]
== copySign

[source.no-repl,motoko]
----
let copySign : (x : Float, y : Float) -> Float
----

Returns `x` if `x` and `y` have same sign, otherwise `x` with negated sign.

[[value.min]]
== min

[source.no-repl,motoko]
----
let min : (x : Float, y : Float) -> Float
----

Returns the smaller value of `x` and `y`.

[[value.max]]
== max

[source.no-repl,motoko]
----
let max : (x : Float, y : Float) -> Float
----

Returns the larger value of `x` and `y`.

[[value.sin]]
== sin

[source.no-repl,motoko]
----
let sin : (x : Float) -> Float
----

Returns the sine of the radian angle `x`.

[[value.cos]]
== cos

[source.no-repl,motoko]
----
let cos : (x : Float) -> Float
----

Returns the cosine of the radian angle `x`.

[[value.tan]]
== tan

[source.no-repl,motoko]
----
let tan : (x : Float) -> Float
----

Returns the tangent of the radian angle `x`.

[[value.arcsin]]
== arcsin

[source.no-repl,motoko]
----
let arcsin : (x : Float) -> Float
----

Returns the arc sine of `x` in radians.

[[value.arccos]]
== arccos

[source.no-repl,motoko]
----
let arccos : (x : Float) -> Float
----

Returns the arc cosine of `x` in radians.

[[value.arctan]]
== arctan

[source.no-repl,motoko]
----
let arctan : (x : Float) -> Float
----

Returns the arc tangent of `x` in radians.

[[value.arctan2]]
== arctan2

[source.no-repl,motoko]
----
let arctan2 : (y : Float, x : Float) -> Float
----

Given `(y,x)`, returns the arc tangent in radians of `y/x` based on the signs of both values to determine the correct quadrant.

[[value.exp]]
== exp

[source.no-repl,motoko]
----
let exp : (x : Float) -> Float
----

Returns the value of `e` raised to the `x`-th power.

[[value.log]]
== log

[source.no-repl,motoko]
----
let log : (x : Float) -> Float
----

Returns the natural logarithm (base-`e`) of `x`.

[[value.format]]
== format

[source.no-repl,motoko]
----
func format(fmt : {#fix : Nat8; #exp : Nat8; #gen : Nat8; #hex : Nat8; #exact}, x : Float) : Text
----

Formatting. `format(fmt, x)` formats `x` to `Text` according to the
formatting directive `fmt`, which can take one of the following forms:

* `#fix prec` as fixed-point format with `prec` digits
* `#exp prec` as exponential format with `prec` digits
* `#gen prec` as generic format with `prec` digits
* `#hex prec` as hexadecimal format with `prec` digits
* `#exact` as exact format that can be decoded without loss.

[[value.toText]]
== toText

[source.no-repl,motoko]
----
let toText : Float -> Text
----

Conversion to Text. Use `format(fmt, x)` for more detailed control.

[[value.toInt64]]
== toInt64

[source.no-repl,motoko]
----
let toInt64 : Float -> Int64
----

Conversion to Int64 by truncating Float, equivalent to `toInt64(trunc(f))`

[[value.fromInt64]]
== fromInt64

[source.no-repl,motoko]
----
let fromInt64 : Int64 -> Float
----

Conversion from Int64.

[[value.toInt]]
== toInt

[source.no-repl,motoko]
----
let toInt : Float -> Int
----

Conversion to Int via Int64, equivalent to `Int64.toInt(toInt64(trunc(f)))`

[[value.fromInt]]
== fromInt

[source.no-repl,motoko]
----
let fromInt : Int -> Float
----

Conversion from Int via Int64. May trap.

[[value.equal]]
== equal

[source.no-repl,motoko]
----
func equal(x : Float, y : Float) : Bool
----

Returns `x == y`.

[[value.notEqual]]
== notEqual

[source.no-repl,motoko]
----
func notEqual(x : Float, y : Float) : Bool
----

Returns `x != y`.

[[value.less]]
== less

[source.no-repl,motoko]
----
func less(x : Float, y : Float) : Bool
----

Returns `x < y`.

[[value.lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko]
----
func lessOrEqual(x : Float, y : Float) : Bool
----

Returns `x <= y`.

[[value.greater]]
== greater

[source.no-repl,motoko]
----
func greater(x : Float, y : Float) : Bool
----

Returns `x > y`.

[[value.greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko]
----
func greaterOrEqual(x : Float, y : Float) : Bool
----

Returns `x >= y`.

[[value.compare]]
== compare

[source.no-repl,motoko]
----
func compare(x : Float, y : Float) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

[[value.neq]]
== neq

[source.no-repl,motoko]
----
func neq(x : Float) : Float
----

Returns the negation of `x`, `-x` .

[[value.add]]
== add

[source.no-repl,motoko]
----
func add(x : Float, y : Float) : Float
----

Returns the sum of `x` and `y`, `x + y`.

[[value.sub]]
== sub

[source.no-repl,motoko]
----
func sub(x : Float, y : Float) : Float
----

Returns the difference of `x` and `y`, `x - y`.

[[value.mul]]
== mul

[source.no-repl,motoko]
----
func mul(x : Float, y : Float) : Float
----

Returns the product of `x` and `y`, `x * y`.

[[value.div]]
== div

[source.no-repl,motoko]
----
func div(x : Float, y : Float) : Float
----

Returns the division of `x` by `y`, `x / y`.

[[value.rem]]
== rem

[source.no-repl,motoko]
----
func rem(x : Float, y : Float) : Float
----

Returns the remainder of `x` divided by `y`, `x % y`.

[[value.pow]]
== pow

[source.no-repl,motoko]
----
func pow(x : Float, y : Float) : Float
----

Returns `x` to the power of `y`, `x ** y`.

