[[module.HashMap]]
= HashMap

Mutable hash map (aka Hashtable)

This module defines an imperative hash map (hash table), with a general key and value type.

It has a minimal object-oriented interface: get, set, swap, delete, count and entries.

The class is parameterized by the key's equality and hash functions,
and an initial capacity.  However, as with `Buf`, no array allocation
happens until the first `set` (or `swap`).

Internally, table growth policy is very simple, for now:
  Double an initial capacity when the expected
  bucket list beyond a certain constant.

[[type.HashMap]]
== HashMap

[source.no-repl,motoko,subs=+macros]
----
class HashMap<K, V>(initCapacity : Nat, keyEq : (K, K) -> Bool, keyHash : K -> xref:Hash.adoc#type.Hash[Hash.Hash])
----

An imperative HashMap with a minimal object-oriented interface.
Maps keys of type `K` to values of type `V`.



[[HashMap.size]]
=== size

[source.no-repl,motoko,subs=+macros]
----
func size() : Nat
----

Returns the number of entries in this HashMap.

[[HashMap.delete]]
=== delete

[source.no-repl,motoko,subs=+macros]
----
func delete(k : K)
----

Deletes the entry with the key `k`. Doesn't do anything if the key doesn't
exist.

[[HashMap.remove]]
=== remove

[source.no-repl,motoko,subs=+macros]
----
func remove(k : K) : ?V
----

Removes the entry with the key `k` and returns the associated value if it
existed or `null` otherwise.

[[HashMap.get]]
=== get

[source.no-repl,motoko,subs=+macros]
----
func get(k : K) : ?V
----

Gets the entry with the key `k` and returns its associated value if it
existed or `null` otherwise.

[[HashMap.put]]
=== put

[source.no-repl,motoko,subs=+macros]
----
func put(k : K, v : V)
----

Insert the value `v` at key `k`. Overwrites an existing entry with key `k`

[[HashMap.replace]]
=== replace

[source.no-repl,motoko,subs=+macros]
----
func replace(k : K, v : V) : ?V
----

Insert the value `v` at key `k` and returns the previous value stored at
`k` or null if it didn't exist.

[[HashMap.entries]]
=== entries

[source.no-repl,motoko,subs=+macros]
----
func entries() : xref:Iter.adoc#type.Iter[Iter.Iter]<(K, V)>
----

Returns an [`Iter`](Iter.html#type.Iter) over the key value pairs in this
HashMap. Does _not_ modify the HashMap.

[[clone]]
== clone

[source.no-repl,motoko,subs=+macros]
----
func clone<K, V>(h : xref:#type.HashMap[HashMap]<K, V>, keyEq : (K, K) -> Bool, keyHash : K -> xref:Hash.adoc#type.Hash[Hash.Hash]) : xref:#type.HashMap[HashMap]<K, V>
----

clone cannot be an efficient object method,
...but is still useful in tests, and beyond.

[[fromIter]]
== fromIter

[source.no-repl,motoko,subs=+macros]
----
func fromIter<K, V>(iter : xref:Iter.adoc#type.Iter[Iter.Iter]<(K, V)>, initCapacity : Nat, keyEq : (K, K) -> Bool, keyHash : K -> xref:Hash.adoc#type.Hash[Hash.Hash]) : xref:#type.HashMap[HashMap]<K, V>
----

Clone from any iterator of key-value pairs

[[map]]
== map

[source.no-repl,motoko,subs=+macros]
----
func map<K, V1, V2>(h : xref:#type.HashMap[HashMap]<K, V1>, keyEq : (K, K) -> Bool, keyHash : K -> xref:Hash.adoc#type.Hash[Hash.Hash], mapFn : (K, V1) -> V2) : xref:#type.HashMap[HashMap]<K, V2>
----



[[mapFilter]]
== mapFilter

[source.no-repl,motoko,subs=+macros]
----
func mapFilter<K, V1, V2>(h : xref:#type.HashMap[HashMap]<K, V1>, keyEq : (K, K) -> Bool, keyHash : K -> xref:Hash.adoc#type.Hash[Hash.Hash], mapFn : (K, V1) -> ?V2) : xref:#type.HashMap[HashMap]<K, V2>
----



