[[module.Int]]
= Int

Integer numbers

Most operations on integers (e.g. addition) are available as built-in operators (e.g. `1 + 1`).
This module provides equivalent functions and `Text` conversion.

[[type.Int]]
== Int

[source.no-repl,motoko,subs=+macros]
----
type Int = Prim.Types.Int
----

Infinite precision signed integers.

[[abs]]
== abs

[source.no-repl,motoko,subs=+macros]
----
let abs : xref:#type.Int[Int] -> Nat
----

Returns the absolute value of the number

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
let toText : xref:#type.Int[Int] -> Text
----

Conversion.

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the minimum of `x` and `y`.

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the maximum of `x` and `y`.

[[hash]]
== hash

[source.no-repl,motoko,subs=+macros]
----
func hash(i : xref:#type.Int[Int]) : xref:Hash.adoc#type.Hash[Hash.Hash]
----

Computes a hash from the least significant 32-bits of `i`, ignoring other bits.
@deprecated For large `Int` values consider using a bespoke hash function that considers all of the argument's bits.

[[hashAcc]]
== hashAcc

[source.no-repl,motoko,subs=+macros]
----
func hashAcc(h1 : xref:Hash.adoc#type.Hash[Hash.Hash], i : xref:#type.Int[Int]) : xref:Hash.adoc#type.Hash[Hash.Hash]
----

@deprecated This function will be removed in future.

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x == y`.

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x != y`.

[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x < y`.

[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x <= y`.

[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x > y`.

[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x >= y`.

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

[[neq]]
== neq

[source.no-repl,motoko,subs=+macros]
----
func neq(x : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the negation of `x`, `-x` .

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the sum of `x` and `y`, `x + y`.

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the difference of `x` and `y`, `x - y`.

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the product of `x` and `y`, `x * y`.

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the division of `x` by `y`,  `x / y`.
Traps when `y` is zero.

[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the remainder of `x` divided by `y`, `x % y`.
Traps when `y` is zero.

[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns `x` to the power of `y`, `x ** y`.

