[[module.Int]]
= Int

Integer numbers

Most operations on integers (e.g. addition) are available as built-in operators (e.g. `1 + 1`).
This module provides equivalent functions and `Text` conversion.

[[abs]]
== abs

[source.no-repl,motoko,subs=+macros]
----
let abs : Int -> Nat
----

Returns the absolute value of the number

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
let toText : Int -> Text
----

Conversion.

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : Int, y : Int) : Int
----

Returns the minimum of `x` and `y`.

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : Int, y : Int) : Int
----

Returns the maximum of `x` and `y`.

[[hash]]
== hash

[source.no-repl,motoko,subs=+macros]
----
func hash(i : Int) : xref:Hash.adoc#type.Hash[Hash.Hash]
----



[[hashAcc]]
== hashAcc

[source.no-repl,motoko,subs=+macros]
----
func hashAcc(h1 : xref:Hash.adoc#type.Hash[Hash.Hash], i : Int) : xref:Hash.adoc#type.Hash[Hash.Hash]
----

WARNING: May go away (?)

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : Int, y : Int) : Bool
----

Returns `x == y`.

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : Int, y : Int) : Bool
----

Returns `x != y`.

[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : Int, y : Int) : Bool
----

Returns `x < y`.

[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : Int, y : Int) : Bool
----

Returns `x <= y`.

[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : Int, y : Int) : Bool
----

Returns `x > y`.

[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : Int, y : Int) : Bool
----

Returns `x >= y`.

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : Int, y : Int) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

[[neq]]
== neq

[source.no-repl,motoko,subs=+macros]
----
func neq(x : Int) : Int
----

Returns the negation of `x`, `-x` .

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : Int, y : Int) : Int
----

Returns the sum of `x` and `y`, `x + y`.

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : Int, y : Int) : Int
----

Returns the difference of `x` and `y`, `x - y`.

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : Int, y : Int) : Int
----

Returns the product of `x` and `y`, `x * y`.

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : Int, y : Int) : Int
----

Returns the division of `x` by `y`,  `x / y`.
Traps when `y` is zero.

[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : Int, y : Int) : Int
----

Returns the remainder of `x` divided by `y`, `x % y`.
Traps when `y` is zero.

[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : Int, y : Int) : Int
----

Returns `x` to the power of `y`, `x ** y`.

