[[module.Int]]
= Int

Signed integer numbers with infinite precision (also called big integers).

Common integer functions.
Most operations on integers (e.g. addition) are also available as built-in operators (e.g. `1 + 1`).

[[type.Int]]
== Int

[source.no-repl,motoko,subs=+macros]
----
type Int = Prim.Types.Int
----

Infinite precision signed integers.

[[abs]]
== abs

[source.no-repl,motoko,subs=+macros]
----
let abs : (x : xref:#type.Int[Int]) -> Nat
----

Returns the absolute value of `x`.

Example:
```motoko
import Int "mo:base/Int";

Int.abs(-12) // => 12
```

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
let toText : xref:#type.Int[Int] -> Text
----

Conversion to Text.
Formats the integer in decimal representation without underscore separators for blocks of thousands.

Example:
```motoko
import Int "mo:base/Int";

Int.toText(-1234) // => "-1234"
```

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the minimum of `x` and `y`.

Example:
```motoko
import Int "mo:base/Int";

Int.min(+2, -3) // => -3
```

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the maximum of `x` and `y`.

Example:
```motoko
import Int "mo:base/Int";

Int.max(+2, -3) // => 2
```

[[hash]]
== hash

[source.no-repl,motoko,subs=+macros]
----
func hash(i : xref:#type.Int[Int]) : xref:Hash.adoc#type.Hash[Hash.Hash]
----

Computes a hash from the least significant 32-bits of `i`, ignoring other bits.
@deprecated For large `Int` values consider using a bespoke hash function that considers all of the argument's bits.

[[hashAcc]]
== hashAcc

[source.no-repl,motoko,subs=+macros]
----
func hashAcc(h1 : xref:Hash.adoc#type.Hash[Hash.Hash], i : xref:#type.Int[Int]) : xref:Hash.adoc#type.Hash[Hash.Hash]
----

Computes an accumulated hash from `h1` and the least significant 32-bits of `i`, ignoring other bits in `i`.
@deprecated For large `Int` values consider using a bespoke hash function that considers all of the argument's bits.

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x == y`.

Example:
```motoko
import Int "mo:base/Int";

Int.equal(123, 123) // => true
```

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x != y`.

Example:
```motoko
import Int "mo:base/Int";

Int.notEqual(123, 123) // => false
```

[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x < y`.

Example:
```motoko
import Int "mo:base/Int";

Int.less(123, 1234) // => true
```

[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x <= y`.

Example:
```motoko
import Int "mo:base/Int";

Int.lessOrEqual(123, 1234) // => true
```

[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x > y`.

Example:
```motoko
import Int "mo:base/Int";

Int.greater(1234, 123) // => true
```

[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : Bool
----

Returns `x >= y`.

Example:
```motoko
import Int "mo:base/Int";

Int.greaterOrEqual(1234, 123) // => true
```

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

Example:
```motoko
import Int "mo:base/Int";

Int.compare(123, 1234) // => #less
```

[[neq]]
== neq

[source.no-repl,motoko,subs=+macros]
----
func neq(x : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the negation of `x`, `-x` .

Example:
```motoko
import Int "mo:base/Int";

Int.neq(123) // => -123
```

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the sum of `x` and `y`, `x + y`.

No overflow since `Int` has infinite precision.

Example:
```motoko
import Int "mo:base/Int";

Int.add(1234, 123) // => 1_357
```

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the difference of `x` and `y`, `x - y`.

No overflow since `Int` has infinite precision.

Example:
```motoko
import Int "mo:base/Int";

Int.sub(1234, 123) // => 1_111
```

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the product of `x` and `y`, `x * y`.

No overflow since `Int` has infinite precision.

Example:
```motoko
import Int "mo:base/Int";

Int.mul(123, 100) // => 12_300
```

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the signed integer division of `x` by `y`,  `x / y`.
Rounds the quotient towards zero, which is the same as truncating the decimal places of the quotient.

Traps when `y` is zero.

Example:
```motoko
import Int "mo:base/Int";

Int.div(123, 10) // => 12
```

[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns the remainder of the signed integer division of `x` by `y`, `x % y`,
which is defined as `x - x / y * y`.

Traps when `y` is zero.

Example:
```motoko
import Int "mo:base/Int";

Int.rem(123, 10) // => 3
```

[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : xref:#type.Int[Int], y : xref:#type.Int[Int]) : xref:#type.Int[Int]
----

Returns `x` to the power of `y`, `x ** y`.

Traps when `y` is negative or `y > 2 ** 32 - 1`.
No overflow since `Int` has infinite precision.

Example:
```motoko
import Int "mo:base/Int";

Int.pow(2, 10) // => 1_024
```

