[[module.Int32]]
= Int32

32-bit signed integers with checked arithmetic

Most operations are available as built-in operators (e.g. `1 + 1`).

[[toInt]]
== toInt

[source.no-repl,motoko,subs=+macros]
----
let toInt : Int32 -> Int
----

Conversion.

[[fromInt]]
== fromInt

[source.no-repl,motoko,subs=+macros]
----
let fromInt : Int -> Int32
----

Conversion. Traps on overflow/underflow.

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
func toText(x : Int32) : Text
----

Returns the Text representation of `x`.

[[abs]]
== abs

[source.no-repl,motoko,subs=+macros]
----
func abs(x : Int32) : Int32
----

Returns the absolute value of `x`. Traps when `x = -2^31`.

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : Int32, y : Int32) : Int32
----

Returns the minimum of `x` and `y`.

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : Int32, y : Int32) : Int32
----

Returns the maximum of `x` and `y`.

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : Int32, y : Int32) : Bool
----

Returns `x == y`.

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : Int32, y : Int32) : Bool
----

Returns `x != y`.

[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : Int32, y : Int32) : Bool
----

Returns `x < y`.

[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : Int32, y : Int32) : Bool
----

Returns `x <= y`.

[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : Int32, y : Int32) : Bool
----

Returns `x > y`.

[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : Int32, y : Int32) : Bool
----

Returns `x >= y`.

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : Int32, y : Int32) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

[[neg]]
== neg

[source.no-repl,motoko,subs=+macros]
----
func neg(x : Int32) : Int32
----

Returns the negation of `x`, `-x`. Traps on overflow.

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : Int32, y : Int32) : Int32
----

Returns the sum of `x` and `y`, `x + y`. Traps on overflow.

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : Int32, y : Int32) : Int32
----

Returns the difference of `x` and `y`, `x - y`. Traps on underflow.

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : Int32, y : Int32) : Int32
----

Returns the product of `x` and `y`, `x * y`. Traps on overflow.

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : Int32, y : Int32) : Int32
----

Returns the division of `x by y`, `x / y`.
Traps when `y` is zero.

[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : Int32, y : Int32) : Int32
----

Returns the remainder of `x` divided by `y`, `x % y`.
Traps when `y` is zero.

[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : Int32, y : Int32) : Int32
----

Returns `x` to the power of `y`, `x ** y`. Traps on overflow.

