[[module.Int32]]
= Int32

32-bit signed integers with checked arithmetic.

Common 32-bit integer functions.
Most operations are available as built-in operators (e.g. `1 + 1`).

[[type.Int32]]
== Int32

[source.no-repl,motoko,subs=+macros]
----
type Int32 = Prim.Types.Int32
----

32-bit signed integers.

[[minimumValue]]
== minimumValue

[source.no-repl,motoko,subs=+macros]
----
let minimumValue : xref:#type.Int32[Int32]
----

Minimum 32-bit integer value, `-2 ** 31`.

[[maximumValue]]
== maximumValue

[source.no-repl,motoko,subs=+macros]
----
let maximumValue : xref:#type.Int32[Int32]
----

Maximum 32-bit integer value, `+2 ** 31 - 1`.

[[toInt]]
== toInt

[source.no-repl,motoko,subs=+macros]
----
let toInt : xref:#type.Int32[Int32] -> Int
----

Converts a 32-bit signed integer to a signed integer with infinite precision.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.toInt(123_456) // => 123_456 : Int
```

[[fromInt]]
== fromInt

[source.no-repl,motoko,subs=+macros]
----
let fromInt : Int -> xref:#type.Int32[Int32]
----

Converts a signed integer with infinite precision to a 32-bit signed integer.

Traps on overflow/underflow.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.fromInt(123_456) // => +123_456 : Int32
```

[[fromIntWrap]]
== fromIntWrap

[source.no-repl,motoko,subs=+macros]
----
let fromIntWrap : Int -> xref:#type.Int32[Int32]
----

Converts a signed integer with infinite precision to a 32-bit signed integer.

Wraps on overflow/underflow.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.fromIntWrap(-123_456) // => -123_456 : Int
```

[[fromNat32]]
== fromNat32

[source.no-repl,motoko,subs=+macros]
----
let fromNat32 : Nat32 -> xref:#type.Int32[Int32]
----

Converts an unsigned 32-bit integer to a signed 32-bit integer.

Wraps on overflow/underflow.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.fromNat32(123_456) // => +123_456 : Int32
```

[[toNat32]]
== toNat32

[source.no-repl,motoko,subs=+macros]
----
let toNat32 : xref:#type.Int32[Int32] -> Nat32
----

Converts a signed 32-bit integer to an unsigned 32-bit integer.

Wraps on overflow/underflow.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.toNat32(-1) // => 4_294_967_295 : Nat32 // underflow
```

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
func toText(x : xref:#type.Int32[Int32]) : Text
----

Returns the Text representation of `x`.
Formats the integer in decimal representation without underscore separators for thousand figures.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.toText(-123456) // => "-123456"
```

[[abs]]
== abs

[source.no-repl,motoko,subs=+macros]
----
func abs(x : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the absolute value of `x`.

Traps when `x == -2 ** 31` (the minimum `Int32` value).

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.abs(-123456) // => +123_456
```

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the minimum of `x` and `y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.min(+2, -3) // => -3
```

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the maximum of `x` and `y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.max(+2, -3) // => +2
```

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : Bool
----

Returns `x == y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.equal(123, 123) // => true
```

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : Bool
----

Returns `x != y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.notEqual(123, 123) // => false
```

[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : Bool
----

Returns `x < y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.less(123, 1234) // => true
```

[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : Bool
----

Returns `x <= y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.lessOrEqual(123, 1234) // => true
```

[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : Bool
----

Returns `x > y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.greater(1234, 123) // => true
```

[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : Bool
----

Returns `x >= y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.greaterOrEqual(1234, 123) // => true
```

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.compare(123, 1234) // => #less
```

[[neg]]
== neg

[source.no-repl,motoko,subs=+macros]
----
func neg(x : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the negation of `x`, `-x`.

Traps on overflow, i.e. for `neg(-2 ** 31)`.


Example:
```motoko
import Int32 "mo:base/Int32";

Int32.neg(123) // => -123
```

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the sum of `x` and `y`, `x + y`.

Traps on overflow/underflow.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.add(1234, 123) // => +1_357
```

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the difference of `x` and `y`, `x - y`.

Traps on overflow/underflow.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.sub(1234, 123) // => +1_111
```

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the product of `x` and `y`, `x * y`.

Traps on overflow/underflow.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.mul(123, 100) // => +12_300
```

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the signed integer division of `x` by `y`, `x / y`.
Rounds the quotient towards zero, which is the same as truncating the decimal places of the quotient.

Traps when `y` is zero.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.div(123, 10) // => +12
```

[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the remainder of the signed integer division of `x` by `y`, `x % y`,
which is defined as `x - x / y * y`.

Traps when `y` is zero.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.rem(123, 10) // => +3
```

[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns `x` to the power of `y`, `x ** y`.

Traps on overflow/underflow and when `y < 0 or y >= 32`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.pow(2, 10) // => +1_024
```

[[bitnot]]
== bitnot

[source.no-repl,motoko,subs=+macros]
----
func bitnot(x : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the bitwise negation of `x`, `^x`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitnot(-256 /* 0xffff_ff00 */) // => +255 // 0xff
```

[[bitand]]
== bitand

[source.no-repl,motoko,subs=+macros]
----
func bitand(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the bitwise "and" of `x` and `y`, `x & y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitand(0xffff, 0x00f0) // => +240 // 0xf0
```

[[bitor]]
== bitor

[source.no-repl,motoko,subs=+macros]
----
func bitor(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the bitwise "or" of `x` and `y`, `x | y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitor(0xffff, 0x00f0) // => +65_535 // 0xffff
```

[[bitxor]]
== bitxor

[source.no-repl,motoko,subs=+macros]
----
func bitxor(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the bitwise "exclusive or" of `x` and `y`, `x ^ y`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitxor(0xffff, 0x00f0) // => +65_295 // 0xff0f
```

[[bitshiftLeft]]
== bitshiftLeft

[source.no-repl,motoko,subs=+macros]
----
func bitshiftLeft(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the bitwise left shift of `x` by `y`, `x << y`.
The right bits of the shift filled with zeros.
Left-overflowing bits, including the sign bit, are discarded.

For `y >= 32`, the semantics is the same as for `bitshiftLeft(x, y % 32)`.
For `y < 0`,  the semantics is the same as for `bitshiftLeft(x, y + y % 32)`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitshiftLeft(1, 8) // => +256 // 0x100 equivalent to `2 ** 8`.
```

[[bitshiftRight]]
== bitshiftRight

[source.no-repl,motoko,subs=+macros]
----
func bitshiftRight(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the signed bitwise right shift of `x` by `y`, `x >> y`.
The sign bit is retained and the left side is filled with the sign bit.
Right-underflowing bits are discarded, i.e. not rotated to the left side.

For `y >= 32`, the semantics is the same as for `bitshiftRight(x, y % 32)`.
For `y < 0`,  the semantics is the same as for `bitshiftRight (x, y + y % 32)`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitshiftRight(1024, 8) // => +4 // equivalent to `1024 / (2 ** 8)`
```

[[bitrotLeft]]
== bitrotLeft

[source.no-repl,motoko,subs=+macros]
----
func bitrotLeft(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the bitwise left rotatation of `x` by `y`, `x <<> y`.
Each left-overflowing bit is inserted again on the right side.
The sign bit is rotated like other bits, i.e. the rotation interprets the number as unsigned.

Changes the direction of rotation for negative `y`.
For `y >= 32`, the semantics is the same as for `bitrotLeft(x, y % 32)`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitrotLeft(0x2000_0001, 4) // => +18 // 0x12.
```

[[bitrotRight]]
== bitrotRight

[source.no-repl,motoko,subs=+macros]
----
func bitrotRight(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the bitwise right rotation of `x` by `y`, `x <>> y`.
Each right-underflowing bit is inserted again on the right side.
The sign bit is rotated like other bits, i.e. the rotation interprets the number as unsigned.

Changes the direction of rotation for negative `y`.
For `y >= 32`, the semantics is the same as for `bitrotRight(x, y % 32)`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitrotRight(0x0002_0001, 8) // => +16_777_728 // 0x0100_0200.
```

[[bittest]]
== bittest

[source.no-repl,motoko,subs=+macros]
----
func bittest(x : xref:#type.Int32[Int32], p : Nat) : Bool
----

Returns the value of bit `p` in `x`, `x & 2**p == 2**p`.
If `p >= 32`, the semantics is the same as for `bittest(x, p % 32)`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bittest(128, 7) // => true
```

[[bitset]]
== bitset

[source.no-repl,motoko,subs=+macros]
----
func bitset(x : xref:#type.Int32[Int32], p : Nat) : xref:#type.Int32[Int32]
----

Returns the value of setting bit `p` in `x` to `1`.
If `p >= 32`, the semantics is the same as for `bitset(x, p % 32)`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitset(0, 7) // => +128
```

[[bitclear]]
== bitclear

[source.no-repl,motoko,subs=+macros]
----
func bitclear(x : xref:#type.Int32[Int32], p : Nat) : xref:#type.Int32[Int32]
----

Returns the value of clearing bit `p` in `x` to `0`.
If `p >= 32`, the semantics is the same as for `bitclear(x, p % 32)`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitclear(-1, 7) // => -129
```

[[bitflip]]
== bitflip

[source.no-repl,motoko,subs=+macros]
----
func bitflip(x : xref:#type.Int32[Int32], p : Nat) : xref:#type.Int32[Int32]
----

Returns the value of flipping bit `p` in `x`.
If `p >= 32`, the semantics is the same as for `bitclear(x, p % 32)`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitflip(255, 7) // => +127
```

[[bitcountNonZero]]
== bitcountNonZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountNonZero : (x : xref:#type.Int32[Int32]) -> xref:#type.Int32[Int32]
----

Returns the count of non-zero bits in `x`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitcountNonZero(0xffff) // => +16
```

[[bitcountLeadingZero]]
== bitcountLeadingZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountLeadingZero : (x : xref:#type.Int32[Int32]) -> xref:#type.Int32[Int32]
----

Returns the count of leading zero bits in `x`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitcountLeadingZero(0x8000) // => +16
```

[[bitcountTrailingZero]]
== bitcountTrailingZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountTrailingZero : (x : xref:#type.Int32[Int32]) -> xref:#type.Int32[Int32]
----

Returns the count of trailing zero bits in `x`.

Example:
```motoko
import Int32 "mo:base/Int32";

Int32.bitcountTrailingZero(0x0201_0000) // => +16
```

[[addWrap]]
== addWrap

[source.no-repl,motoko,subs=+macros]
----
func addWrap(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the sum of `x` and `y`, `x +% y`.

Wraps on overflow/underflow.


Example:
```motoko
import Int32 "mo:base/Int32";

Int32.addWrap(2 ** 30, 2 ** 30) // => -2_147_483_648 // overflow
```

[[subWrap]]
== subWrap

[source.no-repl,motoko,subs=+macros]
----
func subWrap(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the difference of `x` and `y`, `x -% y`.

Wraps on overflow/underflow.


Example:
```motoko
import Int32 "mo:base/Int32";

Int32.subWrap(-2 ** 31, 1) // => +2_147_483_647 // underflow
```

[[mulWrap]]
== mulWrap

[source.no-repl,motoko,subs=+macros]
----
func mulWrap(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns the product of `x` and `y`, `x *% y`. Wraps on overflow.

Wraps on overflow/underflow.


Example:
```motoko
import Int32 "mo:base/Int32";

Int32.mulWrap(2 ** 16, 2 ** 16) // => 0 // overflow
```

[[powWrap]]
== powWrap

[source.no-repl,motoko,subs=+macros]
----
func powWrap(x : xref:#type.Int32[Int32], y : xref:#type.Int32[Int32]) : xref:#type.Int32[Int32]
----

Returns `x` to the power of `y`, `x **% y`.

Wraps on overflow/underflow.
Traps if `y < 0 or y >= 32`.


Example:
```motoko
import Int32 "mo:base/Int32";

Int32.powWrap(2, 31) // => -2_147_483_648 // overflow
```

