[[module.Int8]]
= Int8

8-bit signed integers with checked arithmetic.

Common 8-bit integer functions.
Most operations are available as built-in operators (e.g. `1 + 1`).

[[type.Int8]]
== Int8

[source.no-repl,motoko,subs=+macros]
----
type Int8 = Prim.Types.Int8
----

8-bit signed integers.

[[minimumValue]]
== minimumValue

[source.no-repl,motoko,subs=+macros]
----
let minimumValue : xref:#type.Int8[Int8]
----

Minimum 8-bit integer value, `-2 ** 7`.

[[maximumValue]]
== maximumValue

[source.no-repl,motoko,subs=+macros]
----
let maximumValue : xref:#type.Int8[Int8]
----

Maximum 8-bit integer value, `+2 ** 7 - 1`.

[[toInt]]
== toInt

[source.no-repl,motoko,subs=+macros]
----
let toInt : xref:#type.Int8[Int8] -> Int
----

Converts a 8-bit signed integer to a signed integer with infinite precision.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.toInt(123) // => 123 : Int
```

[[fromInt]]
== fromInt

[source.no-repl,motoko,subs=+macros]
----
let fromInt : Int -> xref:#type.Int8[Int8]
----

Converts a signed integer with infinite precision to a 8-bit signed integer.

Traps on overflow/underflow.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.fromInt(123) // => +123 : Int8
```

[[fromIntWrap]]
== fromIntWrap

[source.no-repl,motoko,subs=+macros]
----
let fromIntWrap : Int -> xref:#type.Int8[Int8]
----

Converts a signed integer with infinite precision to a 8-bit signed integer.

Wraps on overflow/underflow.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.fromIntWrap(-123) // => -123 : Int
```

[[fromNat8]]
== fromNat8

[source.no-repl,motoko,subs=+macros]
----
let fromNat8 : Nat8 -> xref:#type.Int8[Int8]
----

Converts an unsigned 8-bit integer to a signed 8-bit integer.

Wraps on overflow/underflow.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.fromNat8(123) // => +123 : Int8
```

[[toNat8]]
== toNat8

[source.no-repl,motoko,subs=+macros]
----
let toNat8 : xref:#type.Int8[Int8] -> Nat8
----

Converts a signed 8-bit integer to an unsigned 8-bit integer.

Wraps on overflow/underflow.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.toNat8(-1) // => 255 : Nat8 // underflow
```

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
func toText(x : xref:#type.Int8[Int8]) : Text
----

Returns the Text representation of `x`.
Formats the integer in decimal representation.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.toText(-123) // => "-123"
```

[[abs]]
== abs

[source.no-repl,motoko,subs=+macros]
----
func abs(x : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the absolute value of `x`.

Traps when `x == -2 ** 7` (the minimum `Int8` value).

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.abs(-123) // => +123
```

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the minimum of `x` and `y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.min(+2, -3) // => -3
```

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the maximum of `x` and `y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.max(+2, -3) // => +2
```

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : Bool
----

Returns `x == y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.equal(123, 123) // => true
```

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : Bool
----

Returns `x != y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.notEqual(123, 123) // => false
```

[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : Bool
----

Returns `x < y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.less(123, 124) // => true
```

[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : Bool
----

Returns `x <= y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.lessOrEqual(123, 124) // => true
```

[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : Bool
----

Returns `x > y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.greater(124, 123) // => true
```

[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : Bool
----

Returns `x >= y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.greaterOrEqual(124, 123) // => true
```

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.compare(123, 124) // => #less
```

[[neg]]
== neg

[source.no-repl,motoko,subs=+macros]
----
func neg(x : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the negation of `x`, `-x`.

Traps on overflow, i.e. for `neg(-2 ** 7)`.


Example:
```motoko
import Int8 "mo:base/Int8";

Int8.neg(123) // => -123
```

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the sum of `x` and `y`, `x + y`.

Traps on overflow/underflow.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.add(100, 23) // => +123
```

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the difference of `x` and `y`, `x - y`.

Traps on overflow/underflow.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.sub(123, 23) // => +100
```

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the product of `x` and `y`, `x * y`.

Traps on overflow/underflow.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.mul(12, 10) // => +120
```

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the signed integer division of `x` by `y`, `x / y`.
Rounds the quotient towards zero, which is the same as truncating the decimal places of the quotient.

Traps when `y` is zero.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.div(123, 10) // => +12
```

[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the remainder of the signed integer division of `x` by `y`, `x % y`,
which is defined as `x - x / y * y`.

Traps when `y` is zero.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.rem(123, 10) // => +3
```

[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns `x` to the power of `y`, `x ** y`.

Traps on overflow/underflow and when `y < 0 or y >= 8`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.pow(2, 6) // => +64
```

[[bitnot]]
== bitnot

[source.no-repl,motoko,subs=+macros]
----
func bitnot(x : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the bitwise negation of `x`, `^x`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitnot(-16 /* 0xf0 */) // => +15 // 0x0f
```

[[bitand]]
== bitand

[source.no-repl,motoko,subs=+macros]
----
func bitand(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the bitwise "and" of `x` and `y`, `x & y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitand(0x1f, 0x70) // => +16 // 0x10
```

[[bitor]]
== bitor

[source.no-repl,motoko,subs=+macros]
----
func bitor(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the bitwise "or" of `x` and `y`, `x | y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitor(0x0f, 0x70) // => +127 // 0x7f
```

[[bitxor]]
== bitxor

[source.no-repl,motoko,subs=+macros]
----
func bitxor(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the bitwise "exclusive or" of `x` and `y`, `x ^ y`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitxor(0x70, 0x7f) // => +15 // 0x0f
```

[[bitshiftLeft]]
== bitshiftLeft

[source.no-repl,motoko,subs=+macros]
----
func bitshiftLeft(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the bitwise left shift of `x` by `y`, `x << y`.
The right bits of the shift filled with zeros.
Left-overflowing bits, including the sign bit, are discarded.

For `y >= 8`, the semantics is the same as for `bitshiftLeft(x, y % 8)`.
For `y < 0`,  the semantics is the same as for `bitshiftLeft(x, y + y % 8)`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitshiftLeft(1, 4) // => +16 // 0x10 equivalent to `2 ** 4`.
```

[[bitshiftRight]]
== bitshiftRight

[source.no-repl,motoko,subs=+macros]
----
func bitshiftRight(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the signed bitwise right shift of `x` by `y`, `x >> y`.
The sign bit is retained and the left side is filled with the sign bit.
Right-underflowing bits are discarded, i.e. not rotated to the left side.

For `y >= 8`, the semantics is the same as for `bitshiftRight(x, y % 8)`.
For `y < 0`,  the semantics is the same as for `bitshiftRight (x, y + y % 8)`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitshiftRight(64, 4) // => +4 // equivalent to `64 / (2 ** 4)`
```

[[bitrotLeft]]
== bitrotLeft

[source.no-repl,motoko,subs=+macros]
----
func bitrotLeft(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the bitwise left rotatation of `x` by `y`, `x <<> y`.
Each left-overflowing bit is inserted again on the right side.
The sign bit is rotated like other bits, i.e. the rotation interprets the number as unsigned.

Changes the direction of rotation for negative `y`.
For `y >= 8`, the semantics is the same as for `bitrotLeft(x, y % 8)`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitrotLeft(0x11 /* 0b0001_0001 */, 2) // => +68 // 0b0100_0100 == 0x44.
```

[[bitrotRight]]
== bitrotRight

[source.no-repl,motoko,subs=+macros]
----
func bitrotRight(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the bitwise right rotation of `x` by `y`, `x <>> y`.
Each right-underflowing bit is inserted again on the right side.
The sign bit is rotated like other bits, i.e. the rotation interprets the number as unsigned.

Changes the direction of rotation for negative `y`.
For `y >= 8`, the semantics is the same as for `bitrotRight(x, y % 8)`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitrotRight(0x11 /* 0b0001_0001 */, 1) // => -120 // 0b1000_1000 == 0x88.
```

[[bittest]]
== bittest

[source.no-repl,motoko,subs=+macros]
----
func bittest(x : xref:#type.Int8[Int8], p : Nat) : Bool
----

Returns the value of bit `p` in `x`, `x & 2**p == 2**p`.
If `p >= 8`, the semantics is the same as for `bittest(x, p % 8)`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bittest(64, 6) // => true
```

[[bitset]]
== bitset

[source.no-repl,motoko,subs=+macros]
----
func bitset(x : xref:#type.Int8[Int8], p : Nat) : xref:#type.Int8[Int8]
----

Returns the value of setting bit `p` in `x` to `1`.
If `p >= 8`, the semantics is the same as for `bitset(x, p % 8)`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitset(0, 6) // => +64
```

[[bitclear]]
== bitclear

[source.no-repl,motoko,subs=+macros]
----
func bitclear(x : xref:#type.Int8[Int8], p : Nat) : xref:#type.Int8[Int8]
----

Returns the value of clearing bit `p` in `x` to `0`.
If `p >= 8`, the semantics is the same as for `bitclear(x, p % 8)`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitclear(-1, 6) // => -65
```

[[bitflip]]
== bitflip

[source.no-repl,motoko,subs=+macros]
----
func bitflip(x : xref:#type.Int8[Int8], p : Nat) : xref:#type.Int8[Int8]
----

Returns the value of flipping bit `p` in `x`.
If `p >= 8`, the semantics is the same as for `bitclear(x, p % 8)`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitflip(127, 6) // => +63
```

[[bitcountNonZero]]
== bitcountNonZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountNonZero : (x : xref:#type.Int8[Int8]) -> xref:#type.Int8[Int8]
----

Returns the count of non-zero bits in `x`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitcountNonZero(0x0f) // => +4
```

[[bitcountLeadingZero]]
== bitcountLeadingZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountLeadingZero : (x : xref:#type.Int8[Int8]) -> xref:#type.Int8[Int8]
----

Returns the count of leading zero bits in `x`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitcountLeadingZero(0x08) // => +4
```

[[bitcountTrailingZero]]
== bitcountTrailingZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountTrailingZero : (x : xref:#type.Int8[Int8]) -> xref:#type.Int8[Int8]
----

Returns the count of trailing zero bits in `x`.

Example:
```motoko
import Int8 "mo:base/Int8";

Int8.bitcountTrailingZero(0x10) // => +4
```

[[addWrap]]
== addWrap

[source.no-repl,motoko,subs=+macros]
----
func addWrap(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the sum of `x` and `y`, `x +% y`.

Wraps on overflow/underflow.


Example:
```motoko
import Int8 "mo:base/Int8";

Int8.addWrap(2 ** 6, 2 ** 6) // => -128 // overflow
```

[[subWrap]]
== subWrap

[source.no-repl,motoko,subs=+macros]
----
func subWrap(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the difference of `x` and `y`, `x -% y`.

Wraps on overflow/underflow.


Example:
```motoko
import Int8 "mo:base/Int8";

Int8.subWrap(-2 ** 7, 1) // => +127 // underflow
```

[[mulWrap]]
== mulWrap

[source.no-repl,motoko,subs=+macros]
----
func mulWrap(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns the product of `x` and `y`, `x *% y`. Wraps on overflow.

Wraps on overflow/underflow.


Example:
```motoko
import Int8 "mo:base/Int8";

Int8.mulWrap(2 ** 4, 2 ** 4) // => 0 // overflow
```

[[powWrap]]
== powWrap

[source.no-repl,motoko,subs=+macros]
----
func powWrap(x : xref:#type.Int8[Int8], y : xref:#type.Int8[Int8]) : xref:#type.Int8[Int8]
----

Returns `x` to the power of `y`, `x **% y`.

Wraps on overflow/underflow.
Traps if `y < 0 or y >= 8`.


Example:
```motoko
import Int8 "mo:base/Int8";

Int8.powWrap(2, 7) // => -128 // overflow
```

