[[module.Int8]]
= Int8

8-bit signed integers with checked arithmetic

Most operations are available as built-in operators (e.g. `1 + 1`).

[[toInt]]
== toInt

[source.no-repl,motoko,subs=+macros]
----
let toInt : Int8 -> Int
----

Conversion.

[[fromInt]]
== fromInt

[source.no-repl,motoko,subs=+macros]
----
let fromInt : Int -> Int8
----

Conversion. Traps on overflow/underflow.

[[fromIntWrap]]
== fromIntWrap

[source.no-repl,motoko,subs=+macros]
----
let fromIntWrap : Int -> Int8
----

Conversion. Wraps on overflow/underflow.

[[fromNat8]]
== fromNat8

[source.no-repl,motoko,subs=+macros]
----
let fromNat8 : Nat8 -> Int8
----

Conversion. Wraps on overflow/underflow.

[[toNat8]]
== toNat8

[source.no-repl,motoko,subs=+macros]
----
let toNat8 : Int8 -> Nat8
----

Conversion. Wraps on overflow/underflow.

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
func toText(x : Int8) : Text
----

Returns the Text representation of `x`.

[[abs]]
== abs

[source.no-repl,motoko,subs=+macros]
----
func abs(x : Int8) : Int8
----

Returns the absolute value of `x`. Traps when `x = -2^7`.

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : Int8, y : Int8) : Int8
----

Returns the minimum of `x` and `y`.

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : Int8, y : Int8) : Int8
----

Returns the maximum of `x` and `y`.

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : Int8, y : Int8) : Bool
----

Returns `x == y`.

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : Int8, y : Int8) : Bool
----

Returns `x != y`.

[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : Int8, y : Int8) : Bool
----

Returns `x < y`.

[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : Int8, y : Int8) : Bool
----

Returns `x <= y`.

[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : Int8, y : Int8) : Bool
----

Returns `x > y`.

[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : Int8, y : Int8) : Bool
----

Returns `x >= y`.

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : Int8, y : Int8) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

[[neg]]
== neg

[source.no-repl,motoko,subs=+macros]
----
func neg(x : Int8) : Int8
----

Returns the negation of `x`, `-x`. Traps on overflow.

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : Int8, y : Int8) : Int8
----

Returns the sum of `x` and `y`, `x + y`. Traps on overflow.

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : Int8, y : Int8) : Int8
----

Returns the difference of `x` and `y`, `x - y`. Traps on underflow.

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : Int8, y : Int8) : Int8
----

Returns the product of `x` and `y`, `x * y`. Traps on overflow.

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : Int8, y : Int8) : Int8
----

Returns the division of `x by y`, `x / y`.
Traps when `y` is zero.

[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : Int8, y : Int8) : Int8
----

Returns the remainder of `x` divided by `y`, `x % y`.
Traps when `y` is zero.

[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : Int8, y : Int8) : Int8
----

Returns `x` to the power of `y`, `x ** y`. Traps on overflow.

[[bitnot]]
== bitnot

[source.no-repl,motoko,subs=+macros]
----
func bitnot(x : Int8, y : Int8) : Int8
----

Returns the bitwise negation of `x`, `^x`.

[[bitand]]
== bitand

[source.no-repl,motoko,subs=+macros]
----
func bitand(x : Int8, y : Int8) : Int8
----

Returns the bitwise and of `x` and `y`, `x & y`.

[[bitor]]
== bitor

[source.no-repl,motoko,subs=+macros]
----
func bitor(x : Int8, y : Int8) : Int8
----

Returns the bitwise or of `x` and `y`, `x \| y`.

[[bitxor]]
== bitxor

[source.no-repl,motoko,subs=+macros]
----
func bitxor(x : Int8, y : Int8) : Int8
----

Returns the bitwise exclusive or of `x` and `y`, `x ^ y`.

[[bitshiftLeft]]
== bitshiftLeft

[source.no-repl,motoko,subs=+macros]
----
func bitshiftLeft(x : Int8, y : Int8) : Int8
----

Returns the bitwise shift left of `x` by `y`, `x << y`.

[[bitshiftRight]]
== bitshiftRight

[source.no-repl,motoko,subs=+macros]
----
func bitshiftRight(x : Int8, y : Int8) : Int8
----

Returns the bitwise shift right of `x` by `y`, `x >> y`.

[[bitrotLeft]]
== bitrotLeft

[source.no-repl,motoko,subs=+macros]
----
func bitrotLeft(x : Int8, y : Int8) : Int8
----

Returns the bitwise rotate left of `x` by `y`, `x <<> y`.

[[bitrotRight]]
== bitrotRight

[source.no-repl,motoko,subs=+macros]
----
func bitrotRight(x : Int8, y : Int8) : Int8
----

Returns the bitwise rotate right of `x` by `y`, `x <>> y`.

[[bittest]]
== bittest

[source.no-repl,motoko,subs=+macros]
----
func bittest(x : Int8, p : Nat) : Bool
----

Returns the value of bit `p mod 8` in `x`, `(x & 2^(p mod 8)) == 2^(p mod 8)`.

[[bitset]]
== bitset

[source.no-repl,motoko,subs=+macros]
----
func bitset(x : Int8, p : Nat) : Int8
----

Returns the value of setting bit `p mod 8` in `x` to `1`.

[[bitclear]]
== bitclear

[source.no-repl,motoko,subs=+macros]
----
func bitclear(x : Int8, p : Nat) : Int8
----

Returns the value of clearing bit `p mod 8` in `x` to `0`.

[[bitflip]]
== bitflip

[source.no-repl,motoko,subs=+macros]
----
func bitflip(x : Int8, p : Nat) : Int8
----

Returns the value of flipping bit `p mod 8` in `x`.

[[bitcountNonZero]]
== bitcountNonZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountNonZero : (x : Int8) -> Int8
----

Returns the count of non-zero bits in `x`.

[[bitcountLeadingZero]]
== bitcountLeadingZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountLeadingZero : (x : Int8) -> Int8
----

Returns the count of leading zero bits in `x`.

[[bitcountTrailingZero]]
== bitcountTrailingZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountTrailingZero : (x : Int8) -> Int8
----

Returns the count of trailing zero bits in `x`.

[[addWrap]]
== addWrap

[source.no-repl,motoko,subs=+macros]
----
func addWrap(x : Int8, y : Int8) : Int8
----

Returns the sum of `x` and `y`, `x +% y`. Wraps on overflow.

[[subWrap]]
== subWrap

[source.no-repl,motoko,subs=+macros]
----
func subWrap(x : Int8, y : Int8) : Int8
----

Returns the difference of `x` and `y`, `x -% y`. Wraps on underflow.

[[mulWrap]]
== mulWrap

[source.no-repl,motoko,subs=+macros]
----
func mulWrap(x : Int8, y : Int8) : Int8
----

Returns the product of `x` and `y`, `x *% y`. Wraps on overflow.

[[powWrap]]
== powWrap

[source.no-repl,motoko,subs=+macros]
----
func powWrap(x : Int8, y : Int8) : Int8
----

Returns `x` to the power of `y`, `x **% y`. Wraps on overflow. Traps if `y < 0`.

