[[module.Iter]]
= Iter

[[type.Iter]]
== Iter

[source.no-repl,motoko,subs=+macros]
----
type Iter<T> = { next : () -> ?T }
----

 An iterator that produces values of type `T`. Calling `next` returns
 `null` when iteration is finished.

 Iterators are inherently stateful. Calling `next` "consumes" a value from
 the Iterator that cannot be put back, so keep that in mind when sharing
 iterators between consumers.

 An iterater `i` can be iterated over using
 ```
 for (x in i) {
   …do something with x…
 }
 ```

[[type.range]]
== range

[source.no-repl,motoko,subs=+macros]
----
class range(x : Nat, y : Int)
----

 Creates an iterator that produces all `Nat`s from `x` to `y` including
 both of the bounds.
 ```motoko
 import Iter "mo:base/Iter";
 let iter = Iter.range(1, 3);
 assert(?1 == iter.next());
 assert(?2 == iter.next());
 assert(?3 == iter.next());
 assert(null == iter.next());
 ```



[[range.next]]
=== next

[source.no-repl,motoko,subs=+macros]
----
func next() : ?Nat
----



[[type.revRange]]
== revRange

[source.no-repl,motoko,subs=+macros]
----
class revRange(x : Int, y : Int)
----

 Like `range` but produces the values in the opposite
 order.



[[revRange.next]]
=== next

[source.no-repl,motoko,subs=+macros]
----
func next() : ?Int
----



[[iterate]]
== iterate

[source.no-repl,motoko,subs=+macros]
----
func iterate<A>(xs : xref:#type.Iter[Iter]<A>, f : (A, Nat) -> ())
----

 Calls a function `f` on every value produced by an iterator and discards
 the results. If you're looking to keep these results use `map` instead.

 ```motoko
 import Iter "mo:base/Iter";
 var sum = 0;
 Iter.iterate<Nat>(Iter.range(1, 3), func(x, _index) {
   sum += x;
 });
 assert(6 == sum)
 ```

[[size]]
== size

[source.no-repl,motoko,subs=+macros]
----
func size<A>(xs : xref:#type.Iter[Iter]<A>) : Nat
----

 Consumes an iterator and counts how many elements were produced
 (discarding them in the process).

[[map]]
== map

[source.no-repl,motoko,subs=+macros]
----
func map<A, B>(xs : xref:#type.Iter[Iter]<A>, f : A -> B) : xref:#type.Iter[Iter]<B>
----

 Takes a function and an iterator and returns a new iterator that lazily applies
 the function to every element produced by the argument iterator.
 ```motoko
 import Iter "mo:base/Iter";
 let iter = Iter.range(1, 3);
 let mappedIter = Iter.map(iter, func (x : Nat) : Nat { x * 2 });
 assert(?2 == mappedIter.next());
 assert(?4 == mappedIter.next());
 assert(?6 == mappedIter.next());
 assert(null == mappedIter.next());
 ```

[[filter]]
== filter

[source.no-repl,motoko,subs=+macros]
----
func filter<A>(xs : xref:#type.Iter[Iter]<A>, f : A -> Bool) : xref:#type.Iter[Iter]<A>
----

 Takes a function and an iterator and returns a new iterator that produces
 elements from the original iterator if and only if the predicate is true.
 ```motoko
 import Iter "mo:base/Iter";
 let iter = Iter.range(1, 3);
 let mappedIter = Iter.filter(iter, func (x : Nat) : Bool { x % 2 == 1 });
 assert(?1 == mappedIter.next());
 assert(?3 == mappedIter.next());
 assert(null == mappedIter.next());
 ```

[[make]]
== make

[source.no-repl,motoko,subs=+macros]
----
func make<A>(x : A) : xref:#type.Iter[Iter]<A>
----

 Creates an iterator that produces an infinite sequence of `x`.
 ```motoko
 import Iter "mo:base/Iter";
 let iter = Iter.make(10);
 assert(?10 == iter.next());
 assert(?10 == iter.next());
 assert(?10 == iter.next());
 // ...
 ```

[[concat]]
== concat

[source.no-repl,motoko,subs=+macros]
----
func concat<A>(a : xref:#type.Iter[Iter]<A>, b : xref:#type.Iter[Iter]<A>) : xref:#type.Iter[Iter]<A>
----

 Takes two iterators and returns a new iterator that produces
 elements from the original iterators sequentally.
 ```motoko
 import Iter "mo:base/Iter";
 let iter1 = Iter.range(1, 2);
 let iter2 = Iter.range(5, 6);
 let concatenatedIter = Iter.concat(iter1, iter2);
 assert(?1 == concatenatedIter.next());
 assert(?2 == concatenatedIter.next());
 assert(?5 == concatenatedIter.next());
 assert(?6 == concatenatedIter.next());
 assert(null == concatenatedIter.next());
 ```

[[fromArray]]
== fromArray

[source.no-repl,motoko,subs=+macros]
----
func fromArray<A>(xs : pass:[[]Apass:[]]) : xref:#type.Iter[Iter]<A>
----

 Creates an iterator that produces the elements of an `Array` in ascending index order.
 ```motoko
 import Iter "mo:base/Iter";
 let iter = Iter.fromArray([1, 2, 3]);
 assert(?1 == iter.next());
 assert(?2 == iter.next());
 assert(?3 == iter.next());
 assert(null == iter.next());
 ```

[[fromArrayMut]]
== fromArrayMut

[source.no-repl,motoko,subs=+macros]
----
func fromArrayMut<A>(xs : pass:[[]var Apass:[]]) : xref:#type.Iter[Iter]<A>
----

 Like `fromArray` but for `Array`s with mutable elements. Captures
 the elements of the `Array` at the time the iterator is created, so
 further modifications won't be reflected in the iterator.

[[fromList]]
== fromList

[source.no-repl,motoko,subs=+macros]
----
let fromList
----

 Like `fromArray` but for Lists.

[[toArray]]
== toArray

[source.no-repl,motoko,subs=+macros]
----
func toArray<A>(xs : xref:#type.Iter[Iter]<A>) : pass:[[]Apass:[]]
----

 Consumes an iterator and collects its produced elements in an `Array`.
 ```motoko
 import Iter "mo:base/Iter";
 let iter = Iter.range(1, 3);
 assert([1, 2, 3] == Iter.toArray(iter));
 ```

[[toArrayMut]]
== toArrayMut

[source.no-repl,motoko,subs=+macros]
----
func toArrayMut<A>(xs : xref:#type.Iter[Iter]<A>) : pass:[[]var Apass:[]]
----

 Like `toArray` but for `Array`s with mutable elements.

[[toList]]
== toList

[source.no-repl,motoko,subs=+macros]
----
func toList<A>(xs : xref:#type.Iter[Iter]<A>) : xref:List.adoc#type.List[List.List]<A>
----

 Like `toArray` but for Lists.

[[sort]]
== sort

[source.no-repl,motoko,subs=+macros]
----
func sort<A>(xs : xref:#type.Iter[Iter]<A>, compare : (A, A) -> xref:Order.adoc#type.Order[Order.Order]) : xref:#type.Iter[Iter]<A>
----

 Sorted iterator.  Will iterate over *all* elements to sort them, necessarily.

