[[module.List]]
= List

Purely-functional, singly-linked lists.

[[type.List]]
== List

[source.no-repl,motoko,subs=+macros]
----
type List<T> = ?(T, xref:#type.List[List]<T>)
----



[[nil]]
== nil

[source.no-repl,motoko,subs=+macros]
----
func nil<T>() : xref:#type.List[List]<T>
----

Create an empty list.

[[isNil]]
== isNil

[source.no-repl,motoko,subs=+macros]
----
func isNil<T>(l : xref:#type.List[List]<T>) : Bool
----

Check whether a list is empty and return true if the list is empty.

[[push]]
== push

[source.no-repl,motoko,subs=+macros]
----
func push<T>(x : T, l : xref:#type.List[List]<T>) : xref:#type.List[List]<T>
----

Construct a list by pre-pending a value.
This function is similar to a `list.cons(item)` function.

[[last]]
== last

[source.no-repl,motoko,subs=+macros]
----
func last<T>(l : xref:#type.List[List]<T>) : ?T
----

Return the last element of the list, if present.

[[pop]]
== pop

[source.no-repl,motoko,subs=+macros]
----
func pop<T>(l : xref:#type.List[List]<T>) : (?T, xref:#type.List[List]<T>)
----

Treat the list as a stack.
This function combines the `head` and (non-failing) `tail` operations into one operation.

[[size]]
== size

[source.no-repl,motoko,subs=+macros]
----
func size<T>(l : xref:#type.List[List]<T>) : Nat
----

Return the length of the list.

[[get]]
== get

[source.no-repl,motoko,subs=+macros]
----
func get<T>(l : xref:#type.List[List]<T>, n : Nat) : ?T
----

Access any item in a list, zero-based.

NOTE: Indexing into a list is a linear operation, and usually an
indication that a list might not be the best data structure
to use.

[[reverse]]
== reverse

[source.no-repl,motoko,subs=+macros]
----
func reverse<T>(l : xref:#type.List[List]<T>) : xref:#type.List[List]<T>
----

Reverses the list

[[iterate]]
== iterate

[source.no-repl,motoko,subs=+macros]
----
func iterate<T>(l : xref:#type.List[List]<T>, f : T -> ())
----

Call the given function with each list element in turn.

This function is equivalent to the `app` function in Standard ML Basis,
and the `iter` function in OCaml.

[[map]]
== map

[source.no-repl,motoko,subs=+macros]
----
func map<T, S>(l : xref:#type.List[List]<T>, f : T -> S) : xref:#type.List[List]<S>
----

Call the given function on each list element and collect the results
in a new list.

[[filter]]
== filter

[source.no-repl,motoko,subs=+macros]
----
func filter<T>(l : xref:#type.List[List]<T>, f : T -> Bool) : xref:#type.List[List]<T>
----

Create a new list with only those elements of the original list for which
the given function (often called the _predicate_) returns true.

[[partition]]
== partition

[source.no-repl,motoko,subs=+macros]
----
func partition<T>(l : xref:#type.List[List]<T>, f : T -> Bool) : (xref:#type.List[List]<T>, xref:#type.List[List]<T>)
----

Create two new lists from the results of a given function (`f`).
The first list only includes the elements for which the given
function `f` returns true and the second list only includes
the elements for which the function returns false.

[[mapFilter]]
== mapFilter

[source.no-repl,motoko,subs=+macros]
----
func mapFilter<T, S>(l : xref:#type.List[List]<T>, f : T -> ?S) : xref:#type.List[List]<S>
----

Call the given function on each list element, and collect the non-null results
in a new list.

[[mapResult]]
== mapResult

[source.no-repl,motoko,subs=+macros]
----
func mapResult<A, R, E>(xs : xref:#type.List[List]<A>, f : A -> xref:Result.adoc#type.Result[Result.Result]<R, E>) : xref:Result.adoc#type.Result[Result.Result]<xref:#type.List[List]<R>, E>
----

Maps a Result-returning function over a List and returns either
the first error or a list of successful values.

[[append]]
== append

[source.no-repl,motoko,subs=+macros]
----
func append<T>(l : xref:#type.List[List]<T>, m : xref:#type.List[List]<T>) : xref:#type.List[List]<T>
----

Append the elements from one list to another list.

[[flatten]]
== flatten

[source.no-repl,motoko,subs=+macros]
----
func flatten<T>(l : xref:#type.List[List]<xref:#type.List[List]<T>>) : xref:#type.List[List]<T>
----

Concatenate a list of lists.

In some languages, this operation is also known as a `list join`.

[[take]]
== take

[source.no-repl,motoko,subs=+macros]
----
func take<T>(l : xref:#type.List[List]<T>, n : Nat) : xref:#type.List[List]<T>
----

Returns the first `n` elements of the given list.
If the given list has fewer than `n` elements, this function returns
a copy of the full input list.

[[drop]]
== drop

[source.no-repl,motoko,subs=+macros]
----
func drop<T>(l : xref:#type.List[List]<T>, n : Nat) : xref:#type.List[List]<T>
----

Drop the first `n` elements from the given list.

[[foldLeft]]
== foldLeft

[source.no-repl,motoko,subs=+macros]
----
func foldLeft<T, S>(l : xref:#type.List[List]<T>, a : S, f : (S, T) -> S) : S
----

Fold the list left-to-right using the given function (`f`).

[[foldRight]]
== foldRight

[source.no-repl,motoko,subs=+macros]
----
func foldRight<T, S>(l : xref:#type.List[List]<T>, a : S, f : (T, S) -> S) : S
----

Fold the list right-to-left using the given function (`f`).

[[find]]
== find

[source.no-repl,motoko,subs=+macros]
----
func find<T>(l : xref:#type.List[List]<T>, f : T -> Bool) : ?T
----

Return the first element for which the given predicate `f` is true,
if such an element exists.

[[some]]
== some

[source.no-repl,motoko,subs=+macros]
----
func some<T>(l : xref:#type.List[List]<T>, f : T -> Bool) : Bool
----

Return true if there exists a list element for which
the given predicate `f` is true.

[[all]]
== all

[source.no-repl,motoko,subs=+macros]
----
func all<T>(l : xref:#type.List[List]<T>, f : T -> Bool) : Bool
----

Return true if the given predicate `f` is true for all list
elements.

[[merge]]
== merge

[source.no-repl,motoko,subs=+macros]
----
func merge<T>(l1 : xref:#type.List[List]<T>, l2 : xref:#type.List[List]<T>, lte : (T, T) -> Bool) : xref:#type.List[List]<T>
----

Merge two ordered lists into a single ordered list.
This function requires both list to be ordered as specified
by the given relation `lte`.

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare<T>(l1 : xref:#type.List[List]<T>, l2 : xref:#type.List[List]<T>, compElm : (T, T) -> xref:Order.adoc#type.Order[Order.Order]) : xref:Order.adoc#type.Order[Order.Order]
----

Compare two lists using lexicographic ordering specified by the given relation `lte`.

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal<T>(l1 : xref:#type.List[List]<T>, l2 : xref:#type.List[List]<T>, eq : (T, T) -> Bool) : Bool
----

Compare two lists for equality as specified by the given relation `eq` on the elements.

The function `isEq(l1, l2)` is equivalent to `lessThanEq(l1,l2) && lessThanEq(l2,l1)`,
but the former is more efficient.

[[tabulate]]
== tabulate

[source.no-repl,motoko,subs=+macros]
----
func tabulate<T>(n : Nat, f : Nat -> T) : xref:#type.List[List]<T>
----

Generate a list based on a length and a function that maps from
a list index to a list element.

[[make]]
== make

[source.no-repl,motoko,subs=+macros]
----
func make<X>(x : X) : xref:#type.List[List]<X>
----

Create a list with exactly one element.

[[replicate]]
== replicate

[source.no-repl,motoko,subs=+macros]
----
func replicate<X>(n : Nat, x : X) : xref:#type.List[List]<X>
----

Create a list of the given length with the same value in each position.

[[zip]]
== zip

[source.no-repl,motoko,subs=+macros]
----
func zip<X, Y>(xs : xref:#type.List[List]<X>, ys : xref:#type.List[List]<Y>) : xref:#type.List[List]<(X, Y)>
----

Create a list of pairs from a pair of lists.

If the given lists have different lengths, then the created list will have a
length equal to the length of the smaller list.

[[zipWith]]
== zipWith

[source.no-repl,motoko,subs=+macros]
----
func zipWith<X, Y, Z>(xs : xref:#type.List[List]<X>, ys : xref:#type.List[List]<Y>, f : (X, Y) -> Z) : xref:#type.List[List]<Z>
----

Create a list in which elements are calculated from the function `f` and
include elements occuring at the same position in the given lists.

If the given lists have different lengths, then the created list will have a
length equal to the length of the smaller list.

[[split]]
== split

[source.no-repl,motoko,subs=+macros]
----
func split<X>(n : Nat, xs : xref:#type.List[List]<X>) : (xref:#type.List[List]<X>, xref:#type.List[List]<X>)
----

Split the given list at the given zero-based index.

[[chunks]]
== chunks

[source.no-repl,motoko,subs=+macros]
----
func chunks<X>(n : Nat, xs : xref:#type.List[List]<X>) : xref:#type.List[List]<xref:#type.List[List]<X>>
----

Split the given list into chunks of length `n`.
The last chunk will be shorter if the length of the given list
does not divide by `n` evenly.

[[fromArray]]
== fromArray

[source.no-repl,motoko,subs=+macros]
----
func fromArray<A>(xs : pass:[[]Apass:[]]) : xref:#type.List[List]<A>
----

Convert an array into a list.

[[fromVarArray]]
== fromVarArray

[source.no-repl,motoko,subs=+macros]
----
func fromVarArray<A>(xs : pass:[[]var Apass:[]]) : xref:#type.List[List]<A>
----

Convert a mutable array into a list.

[[toArray]]
== toArray

[source.no-repl,motoko,subs=+macros]
----
func toArray<A>(xs : xref:#type.List[List]<A>) : pass:[[]Apass:[]]
----

Create an array from a list.

[[toVarArray]]
== toVarArray

[source.no-repl,motoko,subs=+macros]
----
func toVarArray<A>(xs : xref:#type.List[List]<A>) : pass:[[]var Apass:[]]
----

Create a mutable array from a list.

