[[module.Nat32]]
= Nat32

32-bit unsigned integers with checked arithmetic

Most operations are available as built-in operators (e.g. `1 + 1`).

[[value.toNat]]
== toNat

[source.no-repl,motoko]
----
let toNat : Nat32 -> Nat
----

Conversion.

[[value.fromNat]]
== fromNat

[source.no-repl,motoko]
----
let fromNat : Nat -> Nat32
----

Conversion. Traps on overflow/underflow.

[[value.toText]]
== toText

[source.no-repl,motoko]
----
func toText(x : Nat32) : Text
----

Returns the Text representation of `x`.

[[value.min]]
== min

[source.no-repl,motoko]
----
func min(x : Nat32, y : Nat32) : Nat32
----

Returns the minimum of `x` and `y`.

[[value.max]]
== max

[source.no-repl,motoko]
----
func max(x : Nat32, y : Nat32) : Nat32
----

Returns the maximum of `x` and `y`.

[[value.equal]]
== equal

[source.no-repl,motoko]
----
func equal(x : Nat32, y : Nat32) : Bool
----

Returns `x == y`.

[[value.notEqual]]
== notEqual

[source.no-repl,motoko]
----
func notEqual(x : Nat32, y : Nat32) : Bool
----

Returns `x != y`.

[[value.less]]
== less

[source.no-repl,motoko]
----
func less(x : Nat32, y : Nat32) : Bool
----

Returns `x < y`.

[[value.lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko]
----
func lessOrEqual(x : Nat32, y : Nat32) : Bool
----

Returns `x <= y`.

[[value.greater]]
== greater

[source.no-repl,motoko]
----
func greater(x : Nat32, y : Nat32) : Bool
----

Returns `x > y`.

[[value.greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko]
----
func greaterOrEqual(x : Nat32, y : Nat32) : Bool
----

Returns `x >= y`.

[[value.compare]]
== compare

[source.no-repl,motoko]
----
func compare(x : Nat32, y : Nat32) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

[[value.add]]
== add

[source.no-repl,motoko]
----
func add(x : Nat32, y : Nat32) : Nat32
----

Returns the sum of `x` and `y`, `x + y`. Traps on overflow.

[[value.sub]]
== sub

[source.no-repl,motoko]
----
func sub(x : Nat32, y : Nat32) : Nat32
----

Returns the difference of `x` and `y`, `x - y`. Traps on underflow.

[[value.mul]]
== mul

[source.no-repl,motoko]
----
func mul(x : Nat32, y : Nat32) : Nat32
----

Returns the product of `x` and `y`, `x * y`. Traps on overflow.

[[value.div]]
== div

[source.no-repl,motoko]
----
func div(x : Nat32, y : Nat32) : Nat32
----

Returns the division of `x by y`, `x / y`.
Traps when `y` is zero.

[[value.rem]]
== rem

[source.no-repl,motoko]
----
func rem(x : Nat32, y : Nat32) : Nat32
----

Returns the remainder of `x` divided by `y`, `x % y`.
Traps when `y` is zero.

[[value.pow]]
== pow

[source.no-repl,motoko]
----
func pow(x : Nat32, y : Nat32) : Nat32
----

Returns `x` to the power of `y`, `x ** y`. Traps on overflow.

