[[module.Nat8]]
= Nat8

Provides utility functions on 8-bit unsigned integers.

:::note
Most operations on integer numbers (e.g. addition) are available as built-in operators (e.g. `1 + 1`).
This module provides equivalent functions and `Text` conversion.
:::

:::info [Function form for higher-order use]

Several arithmetic and comparison functions (e.g. `add`, `sub`, `equal`, `less`, `pow`) are defined in this module to enable their use as first-class function values, which is not possible with operators like `+`, `-`, `==`, etc., in Motoko. This allows you to pass these operations to higher-order functions such as `map`, `foldLeft`, or `sort`.
:::

Import from the base library to use this module.

```motoko name=import
import Nat8 "mo:base/Nat8";
```

[[type.Nat8]]
== Nat8

[source.no-repl,motoko,subs=+macros]
----
type Nat8 = Prim.Types.Nat8
----

 8-bit natural numbers.

[[maximumValue]]
== maximumValue

[source.no-repl,motoko,subs=+macros]
----
let maximumValue : xref:#type.Nat8[Nat8]
----

 Maximum 8-bit natural number. `2 ** 8 - 1`.

 Example:
 ```motoko include=import
 Nat8.maximumValue; // => 255 : Nat8
 ```

[[toNat]]
== toNat

[source.no-repl,motoko,subs=+macros]
----
func toNat(_ : xref:#type.Nat8[Nat8]) : Nat
----

 Converts an 8-bit unsigned integer to an unsigned integer with infinite precision.

 Example:
 ```motoko include=import
 Nat8.toNat(123); // => 123 : Nat
 ```

[[fromNat]]
== fromNat

[source.no-repl,motoko,subs=+macros]
----
func fromNat(_ : Nat) : xref:#type.Nat8[Nat8]
----

 Converts an unsigned integer with infinite precision to an 8-bit unsigned integer.

 Traps on overflow.

 Example:
 ```motoko include=import
 Nat8.fromNat(123); // => 123 : Nat8
 ```

[[fromNat16]]
== fromNat16

[source.no-repl,motoko,subs=+macros]
----
func fromNat16(_ : Nat16) : xref:#type.Nat8[Nat8]
----

 Converts a 16-bit unsigned integer to a 8-bit unsigned integer.

 Traps on overflow.

 Example:
 ```motoko include=import
 Nat8.fromNat16(123); // => 123 : Nat8
 ```

[[toNat16]]
== toNat16

[source.no-repl,motoko,subs=+macros]
----
func toNat16(_ : xref:#type.Nat8[Nat8]) : Nat16
----

 Converts an 8-bit unsigned integer to a 16-bit unsigned integer.

 Example:
 ```motoko include=import
 Nat8.toNat16(123); // => 123 : Nat16
 ```

[[fromIntWrap]]
== fromIntWrap

[source.no-repl,motoko,subs=+macros]
----
func fromIntWrap(_ : Int) : xref:#type.Nat8[Nat8]
----

 Converts a signed integer with infinite precision to an 8-bit unsigned integer.

 Wraps on overflow/underflow.

 Example:
 ```motoko include=import
 Nat8.fromIntWrap(123); // => 123 : Nat8
 ```

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
func toText(x : xref:#type.Nat8[Nat8]) : Text
----

 Converts `x` to its textual representation.

 Example:
 ```motoko include=import
 Nat8.toText(123); // => "123" : Text
 ```

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the minimum of `x` and `y`.

 Example:
 ```motoko include=import
 Nat8.min(123, 200); // => 123 : Nat8
 ```

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the maximum of `x` and `y`.

 Example:
 ```motoko include=import
 Nat8.max(123, 200); // => 200 : Nat8
 ```

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : Bool
----

 Equality function for Nat8 types.
 This is equivalent to `x == y`.

 Example:
 ```motoko include=import
 ignore Nat8.equal(1, 1); // => true
 (1 : Nat8) == (1 : Nat8) // => true
 ```


 Example:
 ```motoko include=import
 import Buffer "mo:base/Buffer";

 let buffer1 = Buffer.Buffer<Nat8>(3);
 let buffer2 = Buffer.Buffer<Nat8>(3);
 Buffer.equal(buffer1, buffer2, Nat8.equal) // => true
 ```

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : Bool
----

 Inequality function for Nat8 types.
 This is equivalent to `x != y`.

 Example:
 ```motoko include=import
 ignore Nat8.notEqual(1, 2); // => true
 (1 : Nat8) != (2 : Nat8) // => true
 ```


[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : Bool
----

 "Less than" function for Nat8 types.
 This is equivalent to `x < y`.

 Example:
 ```motoko include=import
 ignore Nat8.less(1, 2); // => true
 (1 : Nat8) < (2 : Nat8) // => true
 ```


[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : Bool
----

 "Less than or equal" function for Nat8 types.
 This is equivalent to `x <= y`.

 Example:
 ```motoko include=import
 ignore Nat.lessOrEqual(1, 2); // => true
 1 <= 2 // => true
 ```


[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : Bool
----

 "Greater than" function for Nat8 types.
 This is equivalent to `x > y`.

 Example:
 ```motoko include=import
 ignore Nat8.greater(2, 1); // => true
 (2 : Nat8) > (1 : Nat8) // => true
 ```


[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : Bool
----

 "Greater than or equal" function for Nat8 types.
 This is equivalent to `x >= y`.

 Example:
 ```motoko include=import
 ignore Nat8.greaterOrEqual(2, 1); // => true
 (2 : Nat8) >= (1 : Nat8) // => true
 ```


[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : {#less; #equal; #greater}
----

 General purpose comparison function for `Nat8`. Returns the `Order` (
 either `#less`, `#equal`, or `#greater`) of comparing `x` with `y`.

 Example:
 ```motoko include=import
 Nat8.compare(2, 3) // => #less
 ```

 This function can be used as value for a high order function, such as a sort function.

 Example:
 ```motoko include=import
 import Array "mo:base/Array";
 Array.sort([2, 3, 1] : [Nat8], Nat8.compare) // => [1, 2, 3]
 ```

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the sum of `x` and `y`, `x + y`.
 Traps on overflow.

 Example:
 ```motoko include=import
 ignore Nat8.add(1, 2); // => 3
 (1 : Nat8) + (2 : Nat8) // => 3
 ```


 Example:
 ```motoko include=import
 import Array "mo:base/Array";
 Array.foldLeft<Nat8, Nat8>([2, 3, 1], 0, Nat8.add) // => 6
 ```

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the difference of `x` and `y`, `x - y`.
 Traps on underflow.

 Example:
 ```motoko include=import
 ignore Nat8.sub(2, 1); // => 1
 (2 : Nat8) - (1 : Nat8) // => 1
 ```


 Example:
 ```motoko include=import
 import Array "mo:base/Array";
 Array.foldLeft<Nat8, Nat8>([2, 3, 1], 20, Nat8.sub) // => 14
 ```

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the product of `x` and `y`, `x * y`.
 Traps on overflow.

 Example:
 ```motoko include=import
 ignore Nat8.mul(2, 3); // => 6
 (2 : Nat8) * (3 : Nat8) // => 6
 ```


 Example:
 ```motoko include=import
 import Array "mo:base/Array";
 Array.foldLeft<Nat8, Nat8>([2, 3, 1], 1, Nat8.mul) // => 6
 ```

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the quotient of `x` divided by `y`, `x / y`.
 Traps when `y` is zero.

 Example:
 ```motoko include=import
 ignore Nat8.div(6, 2); // => 3
 (6 : Nat8) / (2 : Nat8) // => 3
 ```


[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the remainder of `x` divided by `y`, `x % y`.
 Traps when `y` is zero.

 Example:
 ```motoko include=import
 ignore Nat8.rem(6, 4); // => 2
 (6 : Nat8) % (4 : Nat8) // => 2
 ```


[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns `x` to the power of `y`, `x ** y`.
 Traps on overflow.

 Example:
 ```motoko include=import
 ignore Nat8.pow(2, 3); // => 8
 (2 : Nat8) ** (3 : Nat8) // => 8
 ```


[[bitnot]]
== bitnot

[source.no-repl,motoko,subs=+macros]
----
func bitnot(x : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the bitwise negation of `x`, `^x`.

 Example:
 ```motoko include=import
 ignore Nat8.bitnot(0); // => 255
 ^(0 : Nat8) // => 255
 ```


[[bitand]]
== bitand

[source.no-repl,motoko,subs=+macros]
----
func bitand(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the bitwise and of `x` and `y`, `x & y`.

 Example:
 ```motoko include=import
 ignore Nat8.bitand(3, 2); // => 2
 (3 : Nat8) & (2 : Nat8) // => 2
 ```


[[bitor]]
== bitor

[source.no-repl,motoko,subs=+macros]
----
func bitor(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the bitwise or of `x` and `y`, `x | y`.

 Example:
 ```motoko include=import
 ignore Nat8.bitor(3, 2); // => 3
 (3 : Nat8) | (2 : Nat8) // => 3
 ```


[[bitxor]]
== bitxor

[source.no-repl,motoko,subs=+macros]
----
func bitxor(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the bitwise exclusive or of `x` and `y`, `x ^ y`.

 Example:
 ```motoko include=import
 ignore Nat8.bitxor(3, 2); // => 1
 (3 : Nat8) ^ (2 : Nat8) // => 1
 ```


[[bitshiftLeft]]
== bitshiftLeft

[source.no-repl,motoko,subs=+macros]
----
func bitshiftLeft(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the bitwise shift left of `x` by `y`, `x << y`.

 Example:
 ```motoko include=import
 ignore Nat8.bitshiftLeft(1, 2); // => 4
 (1 : Nat8) << (2 : Nat8) // => 4
 ```


[[bitshiftRight]]
== bitshiftRight

[source.no-repl,motoko,subs=+macros]
----
func bitshiftRight(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the bitwise shift right of `x` by `y`, `x >> y`.

 Example:
 ```motoko include=import
 ignore Nat8.bitshiftRight(4, 2); // => 1
 (4 : Nat8) >> (2 : Nat8) // => 1
 ```


[[bitrotLeft]]
== bitrotLeft

[source.no-repl,motoko,subs=+macros]
----
func bitrotLeft(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the bitwise rotate left of `x` by `y`, `x <<> y`.

 Example:
 ```motoko include=import
 ignore Nat8.bitrotLeft(128, 1); // => 1
 (128 : Nat8) <<> (1 : Nat8) // => 1
 ```


[[bitrotRight]]
== bitrotRight

[source.no-repl,motoko,subs=+macros]
----
func bitrotRight(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the bitwise rotate right of `x` by `y`, `x <>> y`.

 Example:
 ```motoko include=import
 ignore Nat8.bitrotRight(1, 1); // => 128
 (1 : Nat8) <>> (1 : Nat8) // => 128
 ```


[[bittest]]
== bittest

[source.no-repl,motoko,subs=+macros]
----
func bittest(x : xref:#type.Nat8[Nat8], p : Nat) : Bool
----

 Returns the value of bit `p mod 8` in `x`, `(x & 2^(p mod 8)) == 2^(p mod 8)`.
 This is equivalent to checking if the `p`-th bit is set in `x`, using 0 indexing.

 Example:
 ```motoko include=import
 Nat8.bittest(5, 2); // => true
 ```

[[bitset]]
== bitset

[source.no-repl,motoko,subs=+macros]
----
func bitset(x : xref:#type.Nat8[Nat8], p : Nat) : xref:#type.Nat8[Nat8]
----

 Returns the value of setting bit `p mod 8` in `x` to `1`.

 Example:
 ```motoko include=import
 Nat8.bitset(5, 1); // => 7
 ```

[[bitclear]]
== bitclear

[source.no-repl,motoko,subs=+macros]
----
func bitclear(x : xref:#type.Nat8[Nat8], p : Nat) : xref:#type.Nat8[Nat8]
----

 Returns the value of clearing bit `p mod 8` in `x` to `0`.

 Example:
 ```motoko include=import
 Nat8.bitclear(5, 2); // => 1
 ```

[[bitflip]]
== bitflip

[source.no-repl,motoko,subs=+macros]
----
func bitflip(x : xref:#type.Nat8[Nat8], p : Nat) : xref:#type.Nat8[Nat8]
----

 Returns the value of flipping bit `p mod 8` in `x`.

 Example:
 ```motoko include=import
 Nat8.bitflip(5, 2); // => 1
 ```

[[bitcountNonZero]]
== bitcountNonZero

[source.no-repl,motoko,subs=+macros]
----
func bitcountNonZero(x : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the count of non-zero bits in `x`.

 Example:
 ```motoko include=import
 Nat8.bitcountNonZero(5); // => 2
 ```

[[bitcountLeadingZero]]
== bitcountLeadingZero

[source.no-repl,motoko,subs=+macros]
----
func bitcountLeadingZero(x : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the count of leading zero bits in `x`.

 Example:
 ```motoko include=import
 Nat8.bitcountLeadingZero(5); // => 5
 ```

[[bitcountTrailingZero]]
== bitcountTrailingZero

[source.no-repl,motoko,subs=+macros]
----
func bitcountTrailingZero(x : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the count of trailing zero bits in `x`.

 Example:
 ```motoko include=import
 Nat8.bitcountTrailingZero(6); // => 1
 ```

[[addWrap]]
== addWrap

[source.no-repl,motoko,subs=+macros]
----
func addWrap(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the sum of `x` and `y`, `x +% y`. Wraps on overflow.

 Example:
 ```motoko include=import
 ignore Nat8.addWrap(230, 26); // => 0
 (230 : Nat8) +% (26 : Nat8) // => 0
 ```


[[subWrap]]
== subWrap

[source.no-repl,motoko,subs=+macros]
----
func subWrap(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the difference of `x` and `y`, `x -% y`. Wraps on underflow.

 Example:
 ```motoko include=import
 ignore Nat8.subWrap(0, 1); // => 255
 (0 : Nat8) -% (1 : Nat8) // => 255
 ```

[[mulWrap]]
== mulWrap

[source.no-repl,motoko,subs=+macros]
----
func mulWrap(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns the product of `x` and `y`, `x *% y`. Wraps on overflow.

 Example:
 ```motoko include=import
 ignore Nat8.mulWrap(230, 26); // => 92
 (230 : Nat8) *% (26 : Nat8) // => 92
 ```


[[powWrap]]
== powWrap

[source.no-repl,motoko,subs=+macros]
----
func powWrap(x : xref:#type.Nat8[Nat8], y : xref:#type.Nat8[Nat8]) : xref:#type.Nat8[Nat8]
----

 Returns `x` to the power of `y`, `x **% y`. Wraps on overflow.

 Example:
 ```motoko include=import
 ignore Nat8.powWrap(2, 8); // => 0
 (2 : Nat8) **% (8 : Nat8) // => 0
 ```


