[[module.Option]]
= Option

 Optional values can be seen as a typesafe `null`. A value of type `?Int` can
 be constructed with either `null` or `?42`. The simplest way to get at the
 contents of an optional is to use pattern matching:

 ```motoko
 let optionalInt1 : ?Int = ?42;
 let optionalInt2 : ?Int = null;

 let int1orZero : Int = switch optionalInt1 {
   case null 0;
   case (?int) int;
 };
 assert int1orZero == 42;

 let int2orZero : Int = switch optionalInt2 {
   case null 0;
   case (?int) int;
 };
 assert int2orZero == 0;
 ```

 The functions in this module capture some common operations when working
 with optionals that can be more succinct than using pattern matching.

[[get]]
== get

[source.no-repl,motoko,subs=+macros]
----
func get<T>(x : ?T, default : T) : T
----

 Unwraps an optional value, with a default value, i.e. `get(?x, d) = x` and
 `get(null, d) = d`.

[[getMapped]]
== getMapped

[source.no-repl,motoko,subs=+macros]
----
func getMapped<A, B>(x : ?A, f : A -> B, default : B) : B
----

 Unwraps an optional value using a function, or returns the default, i.e.
 `option(?x, f, d) = f x` and `option(null, f, d) = d`.

[[map]]
== map

[source.no-repl,motoko,subs=+macros]
----
func map<A, B>(x : ?A, f : A -> B) : ?B
----

 Applies a function to the wrapped value. `null`'s are left untouched.
 ```motoko
 import Option "mo:base/Option";
 assert Option.map<Nat, Nat>(?42, func x = x + 1) == ?43;
 assert Option.map<Nat, Nat>(null, func x = x + 1) == null;
 ```

[[iterate]]
== iterate

[source.no-repl,motoko,subs=+macros]
----
func iterate<A>(x : ?A, f : A -> ())
----

 Applies a function to the wrapped value, but discards the result. Use
 `iterate` if you're only interested in the side effect `f` produces.

 ```motoko
 import Option "mo:base/Option";
 var counter : Nat = 0;
 Option.iterate(?5, func (x : Nat) { counter += x });
 assert counter == 5;
 Option.iterate(null, func (x : Nat) { counter += x });
 assert counter == 5;
 ```

[[apply]]
== apply

[source.no-repl,motoko,subs=+macros]
----
func apply<A, B>(x : ?A, f : ?(A -> B)) : ?B
----

 Applies an optional function to an optional value. Returns `null` if at
 least one of the arguments is `null`.

[[chain]]
== chain

[source.no-repl,motoko,subs=+macros]
----
func chain<A, B>(x : ?A, f : A -> ?B) : ?B
----

 Applies a function to an optional value. Returns `null` if the argument is
 `null`, or the function returns `null`.

[[flatten]]
== flatten

[source.no-repl,motoko,subs=+macros]
----
func flatten<A>(x : ??A) : ?A
----

 Given an optional optional value, removes one layer of optionality.
 ```motoko
 import Option "mo:base/Option";
 assert Option.flatten(?(?(42))) == ?42;
 assert Option.flatten(?(null)) == null;
 assert Option.flatten(null) == null;
 ```

[[make]]
== make

[source.no-repl,motoko,subs=+macros]
----
func make<A>(x : A) : ?A
----

 Creates an optional value from a definite value.
 ```motoko
 import Option "mo:base/Option";
 assert Option.make(42) == ?42;
 ```

[[isSome]]
== isSome

[source.no-repl,motoko,subs=+macros]
----
func isSome(x : ?Any) : Bool
----

 Returns true if the argument is not `null`, otherwise returns false.

[[isNull]]
== isNull

[source.no-repl,motoko,subs=+macros]
----
func isNull(x : ?Any) : Bool
----

 Returns true if the argument is `null`, otherwise returns false.

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal<A>(x : ?A, y : ?A, eq : (A, A) -> Bool) : Bool
----

 Returns true if the optional arguments are equal according to the equality function provided, otherwise returns false.

[[assertSome]]
== assertSome

[source.no-repl,motoko,subs=+macros]
----
func assertSome(x : ?Any)
----

 :::warning [Deprecated function]

`Option.assertSome` will be removed soon. Use an `assert` expression instead.

:::

[[assertNull]]
== assertNull

[source.no-repl,motoko,subs=+macros]
----
func assertNull(x : ?Any)
----

:::warning [Deprecated function]

`Option.assertNull` will be removed soon. Use an `assert` expression instead.
:::

[[unwrap]]
== unwrap

[source.no-repl,motoko,subs=+macros]
----
func unwrap<T>(x : ?T) : T
----

:::warning [Deprecated function]

`Option.unwrap` is unsafe and will be removed soon. Use a `switch` or `do?` expression instead.
:::

