[[module.RBTree]]
= RBTree

Red-Black Trees

[[type.Color]]
== Color

[source.no-repl,motoko]
----
type Color = {#R; #B}
----

Node color: Red or black.

[[type.Tree]]
== Tree

[source.no-repl,motoko]
----
type Tree<X, Y> = {#node : (Color, Tree<X, Y>, (X, ?Y), Tree<X, Y>); #leaf}
----

Ordered, (red-black) tree of entries.

[[class.RBTree]]
== RBTree

[source.no-repl,motoko]
----
class RBTree<X, Y>(compareTo : (X, X) -> O.Order)
----

Create an order map from an order function for its keys.



[[value.share]]
=== share

[source.no-repl,motoko]
----
func share() : Tree<X, Y>
----

Tree as share data.

Get non-OO, purely-functional representation:
for drawing, pretty-printing and non-OO contexts
(e.g., async args and results):

[[value.get]]
=== get

[source.no-repl,motoko]
----
func get(x : X) : ?Y
----

Get the value associated with a given key.

[[value.replace]]
=== replace

[source.no-repl,motoko]
----
func replace(x : X, y : Y) : ?Y
----

Replace the value associated with a given key.

[[value.put]]
=== put

[source.no-repl,motoko]
----
func put(x : X, y : Y)
----

Put an entry: A value associated with a given key.

[[value.delete]]
=== delete

[source.no-repl,motoko]
----
func delete(x : X)
----

Delete the entry associated with a given key.

[[value.remove]]
=== remove

[source.no-repl,motoko]
----
func remove(x : X) : ?Y
----

Remove the entry associated with a given key.

[[value.entries]]
=== entries

[source.no-repl,motoko]
----
func entries() : I.Iter<(X, Y)>
----

An iterator for the key-value entries of the map, in ascending key order.

iterator is persistent, like the tree itself

[[value.entriesRev]]
=== entriesRev

[source.no-repl,motoko]
----
func entriesRev() : I.Iter<(X, Y)>
----

An iterator for the key-value entries of the map, in descending key order.

iterator is persistent, like the tree itself

[[value.iter]]
== iter

[source.no-repl,motoko]
----
func iter<X, Y>(t : Tree<X, Y>, dir : {#fwd; #bwd}) : I.Iter<(X, Y)>
----

An iterator for the entries of the map, in ascending (`#fwd`) or descending (`#bwd`) order.

[[value.size]]
== size

[source.no-repl,motoko]
----
func size<X, Y>(t : Tree<X, Y>) : Nat
----

The size of the tree as the number of key-value entries.

