[[module.RBTree]]
= RBTree

Red-Black Trees

[[type.Color]]
== Color

[source.no-repl,motoko,subs=+macros]
----
type Color = {#R; #B}
----

Node color: red or black.

[[type.Tree]]
== Tree

[source.no-repl,motoko,subs=+macros]
----
type Tree<X, Y> = {#node : (xref:#type.Color[Color], xref:#type.Tree[Tree]<X, Y>, (X, ?Y), xref:#type.Tree[Tree]<X, Y>); #leaf}
----

Ordered, (red-black) tree of entries.

[[type.RBTree]]
== RBTree

[source.no-repl,motoko,subs=+macros]
----
class RBTree<X, Y>(compareTo : (X, X) -> xref:Order.adoc#type.Order[O.Order])
----

Create an order map from an order function for its keys.



[[RBTree.share]]
=== share

[source.no-repl,motoko,subs=+macros]
----
func share() : xref:#type.Tree[Tree]<X, Y>
----

Tree as sharable data.

Get non-OO, purely-functional representation:
for drawing, pretty-printing and non-OO contexts
(e.g., async args and results):

[[RBTree.get]]
=== get

[source.no-repl,motoko,subs=+macros]
----
func get(x : X) : ?Y
----

Get the value associated with a given key.

[[RBTree.replace]]
=== replace

[source.no-repl,motoko,subs=+macros]
----
func replace(x : X, y : Y) : ?Y
----

Replace the value associated with a given key.

[[RBTree.put]]
=== put

[source.no-repl,motoko,subs=+macros]
----
func put(x : X, y : Y)
----

Put an entry: A value associated with a given key.

[[RBTree.delete]]
=== delete

[source.no-repl,motoko,subs=+macros]
----
func delete(x : X)
----

Delete the entry associated with a given key.

[[RBTree.remove]]
=== remove

[source.no-repl,motoko,subs=+macros]
----
func remove(x : X) : ?Y
----

Remove the entry associated with a given key.

[[RBTree.entries]]
=== entries

[source.no-repl,motoko,subs=+macros]
----
func entries() : xref:Iter.adoc#type.Iter[I.Iter]<(X, Y)>
----

An iterator for the key-value entries of the map, in ascending key order.

iterator is persistent, like the tree itself

[[RBTree.entriesRev]]
=== entriesRev

[source.no-repl,motoko,subs=+macros]
----
func entriesRev() : xref:Iter.adoc#type.Iter[I.Iter]<(X, Y)>
----

An iterator for the key-value entries of the map, in descending key order.

iterator is persistent, like the tree itself

[[iter]]
== iter

[source.no-repl,motoko,subs=+macros]
----
func iter<X, Y>(t : xref:#type.Tree[Tree]<X, Y>, dir : {#fwd; #bwd}) : xref:Iter.adoc#type.Iter[I.Iter]<(X, Y)>
----

An iterator for the entries of the map, in ascending (`#fwd`) or descending (`#bwd`) order.

[[size]]
== size

[source.no-repl,motoko,subs=+macros]
----
func size<X, Y>(t : xref:#type.Tree[Tree]<X, Y>) : Nat
----

The size of the tree as the number of key-value entries.

