[[module.Result]]
= Result

 Error handling with the `Result` type.

[[type.Result]]
== Result

[source.no-repl,motoko,subs=+macros]
----
type Result<Ok, Err> = {#ok : Ok; #err : Err}
----

 `Result<Ok, Err>` is the type used for returning and propagating errors. It
 is a type with the variants, `#ok(Ok)`, representing success and containing
 a value, and `#err(Err)`, representing error and containing an error value.

 The simplest way of working with `Result`s is to pattern match on them:

 For example, given a function `createUser(user : User) : Result<Id, String>`
 where `String` is an error message we could use it like so:
 ```motoko no-repl
 switch(createUser(myUser)) {
   case (#ok(id)) { Debug.print("Created new user with id: " # id) };
   case (#err(msg)) { Debug.print("Failed to create user with the error: " # msg) };
 }
 ```

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal<Ok, Err>(eqOk : (Ok, Ok) -> Bool, eqErr : (Err, Err) -> Bool, r1 : xref:#type.Result[Result]<Ok, Err>, r2 : xref:#type.Result[Result]<Ok, Err>) : Bool
----



[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare<Ok, Err>(compareOk : (Ok, Ok) -> xref:Order.adoc#type.Order[Order.Order], compareErr : (Err, Err) -> xref:Order.adoc#type.Order[Order.Order], r1 : xref:#type.Result[Result]<Ok, Err>, r2 : xref:#type.Result[Result]<Ok, Err>) : xref:Order.adoc#type.Order[Order.Order]
----



[[chain]]
== chain

[source.no-repl,motoko,subs=+macros]
----
func chain<R1, R2, Error>(x : xref:#type.Result[Result]<R1, Error>, y : R1 -> xref:#type.Result[Result]<R2, Error>) : xref:#type.Result[Result]<R2, Error>
----

 Allows sequencing of `Result` values and functions that return
 `Result`'s themselves.
 ```motoko
 import Result "mo:base/Result";
 type Result<T,E> = Result.Result<T, E>;
 func largerThan10(x : Nat) : Result<Nat, Text> =
   if (x > 10) { #ok(x) } else { #err("Not larger than 10.") };

 func smallerThan20(x : Nat) : Result<Nat, Text> =
   if (x < 20) { #ok(x) } else { #err("Not smaller than 20.") };

 func between10And20(x : Nat) : Result<Nat, Text> =
   Result.chain(largerThan10(x), smallerThan20);

 assert(between10And20(15) == #ok(15));
 assert(between10And20(9) == #err("Not larger than 10."));
 assert(between10And20(21) == #err("Not smaller than 20."));
 ```

[[flatten]]
== flatten

[source.no-repl,motoko,subs=+macros]
----
func flatten<Ok, Error>(result : xref:#type.Result[Result]<xref:#type.Result[Result]<Ok, Error>, Error>) : xref:#type.Result[Result]<Ok, Error>
----

 Flattens a nested `Result`.

 ```motoko
 import Result "mo:base/Result";
 assert(Result.flatten<Nat, Text>(#ok(#ok(10))) == #ok(10));
 assert(Result.flatten<Nat, Text>(#err("Wrong")) == #err("Wrong"));
 assert(Result.flatten<Nat, Text>(#ok(#err("Wrong"))) == #err("Wrong"));
 ```

[[mapOk]]
== mapOk

[source.no-repl,motoko,subs=+macros]
----
func mapOk<Ok1, Ok2, Error>(x : xref:#type.Result[Result]<Ok1, Error>, f : Ok1 -> Ok2) : xref:#type.Result[Result]<Ok2, Error>
----

 Maps the `Ok` type/value, leaving any `Error` type/value unchanged.

[[mapErr]]
== mapErr

[source.no-repl,motoko,subs=+macros]
----
func mapErr<Ok, Error1, Error2>(x : xref:#type.Result[Result]<Ok, Error1>, f : Error1 -> Error2) : xref:#type.Result[Result]<Ok, Error2>
----

 Maps the `Err` type/value, leaving any `Ok` type/value unchanged.

[[fromOption]]
== fromOption

[source.no-repl,motoko,subs=+macros]
----
func fromOption<R, E>(x : ?R, err : E) : xref:#type.Result[Result]<R, E>
----

 Create a `Result` from an option, including an error value to handle the `null` case.
 ```motoko
 import Result "mo:base/Result";
 assert(Result.fromOption(?42, "err") == #ok(42));
 assert(Result.fromOption(null, "err") == #err("err"));
 ```

[[toOption]]
== toOption

[source.no-repl,motoko,subs=+macros]
----
func toOption<R, E>(r : xref:#type.Result[Result]<R, E>) : ?R
----

 Create an option from a `Result`, turning all #err into `null`.
 ```motoko
 import Result "mo:base/Result";
 assert(Result.toOption(#ok(42)) == ?42);
 assert(Result.toOption(#err("err")) == null);
 ```

[[iterate]]
== iterate

[source.no-repl,motoko,subs=+macros]
----
func iterate<Ok, Err>(res : xref:#type.Result[Result]<Ok, Err>, f : Ok -> ())
----

 Applies a function to a successful value, but discards the result. Use
 `iterate` if you're only interested in the side effect `f` produces.

 ```motoko
 import Result "mo:base/Result";
 var counter : Nat = 0;
 Result.iterate<Nat, Text>(#ok(5), func (x : Nat) { counter += x });
 assert(counter == 5);
 Result.iterate<Nat, Text>(#err("Wrong"), func (x : Nat) { counter += x });
 assert(counter == 5);
 ```

[[isOk]]
== isOk

[source.no-repl,motoko,subs=+macros]
----
func isOk(r : xref:#type.Result[Result]<Any, Any>) : Bool
----



[[isErr]]
== isErr

[source.no-repl,motoko,subs=+macros]
----
func isErr(r : xref:#type.Result[Result]<Any, Any>) : Bool
----



[[assertOk]]
== assertOk

[source.no-repl,motoko,subs=+macros]
----
func assertOk(r : xref:#type.Result[Result]<Any, Any>)
----

 Asserts that its argument is an `#ok` result, traps otherwise.

[[assertErr]]
== assertErr

[source.no-repl,motoko,subs=+macros]
----
func assertErr(r : xref:#type.Result[Result]<Any, Any>)
----

 Asserts that its argument is an `#err` result, traps otherwise.

[[fromUpper]]
== fromUpper

[source.no-repl,motoko,subs=+macros]
----
func fromUpper<Ok, Err>(result : {#Ok : Ok; #Err : Err}) : xref:#type.Result[Result]<Ok, Err>
----

 Converts an upper cased `#Ok`, `#Err` result type into a lowercased `#ok`, `#err` result type.
 On the IC, a common convention is to use `#Ok` and `#Err` as the variants of a result type,
 but in Motoko, we use `#ok` and `#err` instead.

[[toUpper]]
== toUpper

[source.no-repl,motoko,subs=+macros]
----
func toUpper<Ok, Err>(result : xref:#type.Result[Result]<Ok, Err>) : {#Ok : Ok; #Err : Err}
----

 Converts a lower cased `#ok`, `#err` result type into an upper cased `#Ok`, `#Err` result type.
 On the IC, a common convention is to use `#Ok` and `#Err` as the variants of a result type,
 but in Motoko, we use `#ok` and `#err` instead.

