[[module.Word8]]
= Word8

8-bit binary unsigned integers with modular arithmetic

Most operations are available as built-in operators (e.g. `1 | 1`).

[[toNat]]
== toNat

[source.no-repl,motoko,subs=+macros]
----
let toNat : Word8 -> Nat
----

Conversion.

[[fromNat]]
== fromNat

[source.no-repl,motoko,subs=+macros]
----
let fromNat : Nat -> Word8
----

Conversion. Wraps around.

[[toInt]]
== toInt

[source.no-repl,motoko,subs=+macros]
----
func toInt(x : Word8) : Int
----

Conversion. Return a value between `-128` and `127`

[[fromInt]]
== fromInt

[source.no-repl,motoko,subs=+macros]
----
let fromInt : (x : Int) -> Word8
----

Conversion. Returns `x mod 2^8`.

[[toText]]
== toText

[source.no-repl,motoko,subs=+macros]
----
func toText(x : Word8) : Text
----

Returns the Text representation of `x`.

[[min]]
== min

[source.no-repl,motoko,subs=+macros]
----
func min(x : Word8, y : Word8) : Word8
----

Returns the minimum of `x` and `y`.

[[max]]
== max

[source.no-repl,motoko,subs=+macros]
----
func max(x : Word8, y : Word8) : Word8
----

Returns the maximum of `x` and `y`.

[[equal]]
== equal

[source.no-repl,motoko,subs=+macros]
----
func equal(x : Word8, y : Word8) : Bool
----

Returns `x == y`.

[[notEqual]]
== notEqual

[source.no-repl,motoko,subs=+macros]
----
func notEqual(x : Word8, y : Word8) : Bool
----

Returns `x != y`.

[[less]]
== less

[source.no-repl,motoko,subs=+macros]
----
func less(x : Word8, y : Word8) : Bool
----

Returns `x < y`.

[[lessOrEqual]]
== lessOrEqual

[source.no-repl,motoko,subs=+macros]
----
func lessOrEqual(x : Word8, y : Word8) : Bool
----

Returns `x <= y`.

[[greater]]
== greater

[source.no-repl,motoko,subs=+macros]
----
func greater(x : Word8, y : Word8) : Bool
----

Returns `x > y`.

[[greaterOrEqual]]
== greaterOrEqual

[source.no-repl,motoko,subs=+macros]
----
func greaterOrEqual(x : Word8, y : Word8) : Bool
----

Returns `x >= y`.

[[compare]]
== compare

[source.no-repl,motoko,subs=+macros]
----
func compare(x : Word8, y : Word8) : {#less; #equal; #greater}
----

Returns the order of `x` and `y`.

[[add]]
== add

[source.no-repl,motoko,subs=+macros]
----
func add(x : Word8, y : Word8) : Word8
----

Returns the sum of `x` and `y`, `(x + y) mod 2^8`.

[[sub]]
== sub

[source.no-repl,motoko,subs=+macros]
----
func sub(x : Word8, y : Word8) : Word8
----

Returns the difference of `x` and `y`, `(2^8 + x - y) mod 2^8`.

[[mul]]
== mul

[source.no-repl,motoko,subs=+macros]
----
func mul(x : Word8, y : Word8) : Word8
----

Returns the product of `x` and `y`, `(x * y) mod 2^8`.

[[div]]
== div

[source.no-repl,motoko,subs=+macros]
----
func div(x : Word8, y : Word8) : Word8
----

Returns the division of `x` by `y`, `x / y`.
Traps when `y` is zero.

[[rem]]
== rem

[source.no-repl,motoko,subs=+macros]
----
func rem(x : Word8, y : Word8) : Word8
----

Returns the remainder of `x` divided by `y`, `x % y`.
Traps when `y` is zero.

[[pow]]
== pow

[source.no-repl,motoko,subs=+macros]
----
func pow(x : Word8, y : Word8) : Word8
----

Returns `x` to the power of `y`, `(x ** y) mod 2^8`.

[[bitnot]]
== bitnot

[source.no-repl,motoko,subs=+macros]
----
func bitnot(x : Word8, y : Word8) : Word8
----

Returns the bitwise negation of `x`, `^x`.

[[bitand]]
== bitand

[source.no-repl,motoko,subs=+macros]
----
func bitand(x : Word8, y : Word8) : Word8
----

Returns the bitwise and of `x` and `y`, `x & y`.

[[bitor]]
== bitor

[source.no-repl,motoko,subs=+macros]
----
func bitor(x : Word8, y : Word8) : Word8
----

Returns the bitwise or of `x` and `y`, `x \| y`.

[[bitxor]]
== bitxor

[source.no-repl,motoko,subs=+macros]
----
func bitxor(x : Word8, y : Word8) : Word8
----

Returns the bitwise exclusive or of `x` and `y`, `x ^ y`.

[[bitshiftLeft]]
== bitshiftLeft

[source.no-repl,motoko,subs=+macros]
----
func bitshiftLeft(x : Word8, y : Word8) : Word8
----

Returns the bitwise shift left of `x` by `y`, `x << y`.

[[bitshiftRight]]
== bitshiftRight

[source.no-repl,motoko,subs=+macros]
----
func bitshiftRight(x : Word8, y : Word8) : Word8
----

Returns the bitwise shift right of `x` by `y`, `x >> y`.

[[bitshiftRightSigned]]
== bitshiftRightSigned

[source.no-repl,motoko,subs=+macros]
----
func bitshiftRightSigned(x : Word8, y : Word8) : Word8
----

Returns the signed shift right of `x` by `y`, `x +>> y`.

[[bitrotLeft]]
== bitrotLeft

[source.no-repl,motoko,subs=+macros]
----
func bitrotLeft(x : Word8, y : Word8) : Word8
----

Returns the bitwise rotate left of `x` by `y`, `x <<> y`.

[[bitrotRight]]
== bitrotRight

[source.no-repl,motoko,subs=+macros]
----
func bitrotRight(x : Word8, y : Word8) : Word8
----

Returns the bitwise rotate right of `x` by `y`, `x <>> y`.

[[bittest]]
== bittest

[source.no-repl,motoko,subs=+macros]
----
func bittest(x : Word8, p : Nat) : Bool
----

Returns the value of bit `p mod 8` in `x`, `(x & 2^(p mod 8)) == 2^(p mod 8)`.

[[bitset]]
== bitset

[source.no-repl,motoko,subs=+macros]
----
func bitset(x : Word8, p : Nat) : Word8
----

Returns the value of setting bit `p mod 8` in `x` to `1`.

[[bitclear]]
== bitclear

[source.no-repl,motoko,subs=+macros]
----
func bitclear(x : Word8, p : Nat) : Word8
----

Returns the value of clearing bit `p mod 8` in `x` to `0`.

[[bitflip]]
== bitflip

[source.no-repl,motoko,subs=+macros]
----
func bitflip(x : Word8, p : Nat) : Word8
----

Returns the value of flipping bit `p mod 8` in `x`.

[[bitcountNonZero]]
== bitcountNonZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountNonZero : (x : Word8) -> Word8
----

Returns the count of non-zero bits in `x`.

[[bitcountLeadingZero]]
== bitcountLeadingZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountLeadingZero : (x : Word8) -> Word8
----

Returns the count of leading zero bits in `x`.

[[bitcountTrailingZero]]
== bitcountTrailingZero

[source.no-repl,motoko,subs=+macros]
----
let bitcountTrailingZero : (x : Word8) -> Word8
----

Returns the count of trailing zero bits in `x`.

