[[module.Buffer]]
= Buffer

Growing buffers

This module defines buffers that grow, with a general element type.

## Why?

Motoko applications expose interfaces that use fixed-size arrays of
general (user-defined) elements to represent sets, sequences and maps
of application-specific elements.

The `Array` module focuses on Motoko's builtin arrays, whose size is
each fixed.  They do not permit general growth/appending, which is the
focus here.

To create these arrays, and to consume them with ergonomic (imperative) code, and
low API friction, developers need _buffers that grow_.

## Define `Buf<X>` object type

A "buffer" is a mutable sequence that grows, either one element at a
time, or one (second) buffer at time.

[[type.Buffer]]
== Buffer

[source.no-repl,motoko,subs=+macros]
----
class Buffer<X>(initCapacity : Nat)
----

Create a buffer represented internally by an mutable array.

The argument `initCapacity` gives the initial capacity.  Under the
interface, the mutable array grows by doubling when this initial
capacity is exhausted.



[[Buffer.add]]
=== add

[source.no-repl,motoko,subs=+macros]
----
func add(elem : X)
----

Adds a single element to the buffer.

[[Buffer.removeLast]]
=== removeLast

[source.no-repl,motoko,subs=+macros]
----
func removeLast() : ?X
----

Removes the item that was inserted last and returns it or `null` if no
elements had been added to the Buffer.

[[Buffer.append]]
=== append

[source.no-repl,motoko,subs=+macros]
----
func append(b : xref:#type.Buffer[Buffer]<X>)
----

Adds all elements in buffer `b` to this buffer.

[[Buffer.size]]
=== size

[source.no-repl,motoko,subs=+macros]
----
func size() : Nat
----

Returns the current number of elements.

[[Buffer.clear]]
=== clear

[source.no-repl,motoko,subs=+macros]
----
func clear()
----

Resets the buffer.

[[Buffer.clone]]
=== clone

[source.no-repl,motoko,subs=+macros]
----
func clone() : xref:#type.Buffer[Buffer]<X>
----

Returns a copy of this buffer.

[[Buffer.vals]]
=== vals

[source.no-repl,motoko,subs=+macros]
----
func vals() : { next : () -> ?X }
----

Returns an [Iter](Iter.html#type.Iter) over the elements of this buffer.

[[Buffer.toArray]]
=== toArray

[source.no-repl,motoko,subs=+macros]
----
func toArray() : [X]
----

Creates a new array containing this buffer's elements.

[[Buffer.toVarArray]]
=== toVarArray

[source.no-repl,motoko,subs=+macros]
----
func toVarArray() : [var X]
----

Creates a mutable array containing this buffer's elements.

[[Buffer.get]]
=== get

[source.no-repl,motoko,subs=+macros]
----
func get(i : Nat) : X
----

Gets the `i`-th element of this buffer. Traps if  `i >= count`. Indexing is zero-based.

[[Buffer.getOpt]]
=== getOpt

[source.no-repl,motoko,subs=+macros]
----
func getOpt(i : Nat) : ?X
----

Gets the 'i'-th element of the buffer as an option. Returns `null` when `i >= count`. Indexing is zero-based.

[[Buffer.put]]
=== put

[source.no-repl,motoko,subs=+macros]
----
func put(i : Nat, elem : X)
----

Overwrites the current value of the `i`-entry of  this buffer with `elem`. Traps if the
index is out of bounds. Indexing is zero-based.

